---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sa-learn
  namespace: mailserver
spec:
  concurrencyPolicy: Forbid
  schedule: "0 2 * * *"
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: docker-mailserver
            image: mailserver/docker-mailserver:9.0.1
            command: [ 'sa-learn' ]
            args:
              - --spam
              - /var/mail/sko.ai/v/.Junk
              - --dbpath
              - /var/mail-state/lib-amavis/.spamassassin
            volumeMounts:
              - name: data
                mountPath: /var/mail
                subPath: data
              - name: data
                mountPath: /var/mail-state
                subPath: state
              - name: data
                mountPath: /var/log/mail
                subPath: log
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: mail-storage
          restartPolicy: Never
      parallelism: 1
