# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
      version: v1.20.1
  interval: 24h
  values:
    image:
      repository: ghcr.io/vaskozl/cert-manager-controller
      tag: 1.20.1@sha256:63ec6a3cb133b84181e9c686ce058be1e608e35036c298908c9de11a497c4045
    cainjector:
      replicaCount: 1
      image:
        repository: ghcr.io/vaskozl/cert-manager-cainjector
        tag: 1.20.1@sha256:4f151b7ef07bb8ce773ee29ac092e98c0939432a6ba4bdf05f495773e3e5eaca
    acmesolver:
      image:
        repository: ghcr.io/vaskozl/cert-manager-acmesolver
        tag: 1.20.1@sha256:7b426393950a9017275eff4629b1a77226d60658adc3a9327f07061e36e67b0a
    webhook:
      image:
        repository: ghcr.io/vaskozl/cert-manager-webhook
        tag: 1.20.1@sha256:0905aa061d62c087cd06b2462ab2c0db79a393d800263b3a7d2175aa30831556
    installCRDs: true
    extraArgs:
      - --dns01-recursive-nameservers=1.1.1.1:53
    podDnsPolicy: None
    podDnsConfig:
      nameservers:
        - 1.1.1.1
        - 8.8.8.8
    # Enabled once prometheus-operator is installed
    prometheus:
      enabled: false
      servicemonitor:
        enabled: false
        namespace: cert-manager
    config:
      apiVersion: controller.config.cert-manager.io/v1alpha1
      kind: ControllerConfiguration
      enableGatewayAPI: true
