---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: rekon-redis
  namespace: ai
spec:
  replicas: 2
  image: ghcr.io/vaskozl/dragonfly:1.39.0@sha256:e5e7ef50695161b13a400bbe7e1543611a3376885870a5b4af52d5692c7cb708
  nodeSelector:
    kubernetes.io/arch: amd64
  args:
    - --proactor_threads=1
    - --cluster_mode=emulated
    - --lock_on_hashtags
  resources:
    requests:
      cpu: 10m
      memory: 600Mi
    limits:
      memory: 600Mi
  snapshot:
    cron: "*/5 * * * *"
    persistentVolumeClaimSpec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
