---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: rekon-redis
  namespace: ai
spec:
  replicas: 2
  image: ghcr.io/vaskozl/dragonfly:1.39.0@sha256:2aae382d2a321399cfd431b5cd213aec3921fbd189bcc4eeaddf2b5fe75f14f0
  args:
    - "--proactor_threads=2"
  resources:
    requests:
      cpu: 50m
      memory: 600Mi
    limits:
      memory: 600Mi
  snapshot:
    cron: "*/5 * * * *"
    persistentVolumeClaimSpec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
