apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: rekon
spec:
  endpoints:
    - port: http
      path: /metrics
  namespaceSelector:
    matchNames:
      - ai
  selector:
    matchLabels:
      app.kubernetes.io/name: rekon
