apiVersion: v1
kind: ConfigMap
metadata:
    name: authelia-config
    namespace: authelia
data:
    configuration.yml: ENC[AES256_GCM,data:LZ4W9pRZzR2Qt4FnQHfAoehIlVxM2J9MYZXW0bnt8Lw85iFZpoXdVTvuf/78HZ325izpNncmbQhOdkFxaof801MnPYP6qlMv6mwsorxJ7ikg3+6Oi+OF0qpd1w08wK/qeuJGdnXfaYuVfmIMYSxGQPFXmD5lkcOXjZ+AilbCioW65b4ymhThLRzDwNpL4OPZazbL/U9YVmbiB83RidO9bBJ1rlw4IwLLr8t+IBRd3RwpqtGos/f47J+sRla6VdISGZnXK3/kXuV95Obg0rJKW/CXNAK0vpCNSnhVDYsvNXZey+8BoFM7DYWxgToEKb3tjGGOEkXm8whgPL8RPSZkVo+WESph3AAh0Xy3gASGRdyhh9ZidASaH9hpZ37wgVXhnNwnqMwb+CHX68qjxeQI8U4poq7M2OAbfi/sW/b//Gyw9YkL5mF41ef17CuP8Ta5kh3Dk2iD884n4SAQ9lKgOGmuBLPnB2hQCJStkGfBlrrmvSB3k7nufPkfgQl9KiXqHPFgGL1HPrssA61FrT6NvKh7nP3rAniGfL/iFokuA4lIcdiRSLHwewvlUv5ApaITgWNajuGz7rhcf8AO91GmFARh4LMdb+ePvj1s7wuLXJPCi/fd4H8K/wRkr01GL8F0A0DxW1xTnxEslra6gSMqIkL6f2X8XLNlwfzxd8SSPjZ1zZ317xZiuUT+jfSGqjZLvnkwB7hD4/OEs44/RuYeI49F1uuxN+sBLjW0d/kKtC2sbruyTdQ9DZZBAHGLedovdRn9rq3ft4tjGnMXfjkgnXvyNOxuIReRIouRPjY6PTQP/7JKTZPgc23ZQUJFirhjdcySnYkNruSaNHunTIeWIXLqPif6lHz0IOBZHV63nRspCPIpUwMhjwV2/3iIAk+K+JHLi2VEiynZ8Eip4zwpwpvqlueNA0oCgGubjc9dtGtj4eIpPVc283cL5lCQVQEPiU+kuulFx7apar2yMMmpKLm6YqhXK/Gr8zNOsLENz59MHZ6+gtiyV4XYwLa7L3auOaMHMtnyXm1b0RuM8FEunuy2T6cohmXLIxXlkPzc4la24u3hRY9Zfl5svjQBW7z18Zr7Sn8+Av7CleYSm2WnqhIjt4sDGynNb0IEPlZom2nmIzVvmVWRpg47XiMGNyyO7EKmwrtrRYni57iPV0JD+m1gF+3Key/jksuMNDPQLrtACID8yK/1ZlIOPxNKv9NYI51kZIYUV4uTcmAqFYeGRAbwiDh5+wGiThO9A935v66ccS2O9FnjGMwIdAc/ElZdsITv/4UfEoS5UumALiZHvw7tPmS8FhHTEUVGNV+aWmgtWCkExyjxJ+d2fbMPW62NgKitEZDcE4QxC49PXa5tqT2qZDJaiXqpa1RU2wSz0DA8v2bNnTfipw7gDJCEMnkfTlldQrDI3ANSp9o7a3R0fowbkViTYfQ3/OpzkXBdqe/ldj93c6XWy0VxoVfbhGGpUfDtkurVxUrSauMISfUWant47JcdEZSe9U0PEQ2n30l2sSEF8ZqTXwAQRuj3eLoUq09hhDAIpDz95SVgHBtCyHnufoYOGlf9wdNDjqjhedYYPDmWzLN3LLqSYGM0u+Ts5l/OdNGlkNL0d5bTL09gVV9+UpSIsghkS55eHa2dKi8sAqrdl8cPhMae48/HyZ8+z7d+3GDygO1W4PD2YNdZhXx1CITQVD3NjYYh37s/MllNPFaqW3mBGcR2VLiOX+birUgRd2eNXiRXIV60nfDzJ/dkvIDh2D3DzPumTPNPQlh02plH67JALSCxxZAddwRwMtPdqGxjNI4dns7qI0SBUCqrkhR0WbMRoa3+wAT18qOsxq33TzVSFcCZn3CiSMWI0C3dUtChVf5u+uHlMEOs4zmV4uiHZy5eiI3h5OU+uPgdm5UsUpjkFL7kCJeDezIhtuZhTooD4YeGoCVZ4r4I8XZxT7lvRCMLeJAfLQaKCZWxO0was9Bt8vWGchbTzbtDNFw2Yx5HGCIQPjMxAqnky4MXJOR7iQDWEg==,iv:jnjnwezPGcc0w2eTjtHdu5S+eQMhpiwiHAj9innzMqU=,tag:D/TKrYlHeFw6BHfKkrmN2A==,type:str]
    users_database.yml: ENC[AES256_GCM,data:R69qGaew6sTr+GhIJlvRpkdhEI7FAjhv2O60W4u7h5zOomeFELC9tg8Zl9ntpAU7TFoMaMhL6nD52xrik/dAKfyHVEtpmJD2NVuOYhsx2Wc2ZJxDGczVpWu+QTIKgttKFTgLIQpbERjuLtBfbukwdm1STStEOyp2Qm+78Xo420BGqaz2cLhVBqwDRL5gA3m+sR1sXHIr2XVh2S3V+4oV+fFr7VeNRHCBClKDQ1DfjpZ344+jBUw1okxDiwgfSIvZ512+u3YBvcD3GGc0Pe2isPnt4MZGCUaq1TSVz6w17+7kvxpmc3Tg9aL5/sJ+JW7fzCZtx4PCdI2EGGi9EfQMvkGv1wWyvQJvt/DHqfprtXqHPprxxUYfXjJBQI6zlbZ3clcNg05UvN0WioGIZ460mQ0jjxDFmwlfE/VRYyyI2LPpjYazqX/gMfXGqdgnz3T5n5nMPvk+m2ELLsaZ3MBUlkWcz+cuR+N5V3AGn1jEefA0abcbMv6CUtJIzQckBoE50MnA7+QYwyzm2DVgXWj+/+5pAm3BbTnB1cy8vNBVylbY3A0NGeoGF1wgTLhoUpz0qPGgAnuSKiZy5bJkgWLbA88RiGL6dSwDN3zSNZgRq8uAQ+lrWYwJobacU73u6Og=,iv:ctnnrxdcl/Rfihly2R/4KdxgDcjlpPF7raCPHMtizZ8=,tag:KKmrG9xrdz2KtfsHTZ1Tag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-04-02T23:28:43Z'
    mac: ENC[AES256_GCM,data:cZSvrKLOQmiXU6sQ29VzgKxJt49CcnzTzOdPTsvo1B0XT5r4tqLTbv5xNcauL48LFHAFL4Ae6pw6x30t38kJBCa7W+PP4+TjE30EzWyl3+FhufHzRgylKwlJi//Ag/scCLnSvBvnJnkN+8BBrfLo7I6WyKD98azW7k9Z4OOvOJs=,iv:5H2CdzNkTHd2VnwDOcFWT835vknJGMDc/WdX6FU0d5E=,tag:0tt+Tmji8BD9vCYk9PuJVw==,type:str]
    pgp:
    -   created_at: '2021-03-20T20:10:27Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQMOA4x50yY5upzjEAv/ZgJisC3UQDUCOpL0Ui+dinnRTDhtkXRmVTbC7ORXAmOU
            rbANQylqI2lGOt+kX2v/PUSP/0DSSzxnrhxl/+iADRs1sfmR1Vg1cQYc4JlGuVvG
            AeX+siGsdh94Ekc6Xhx6v8m8UV4IH5l2ACDFnqGdQI9ETVtmd4SezTnnL25irYfn
            28/CVJd0GY2CKybcWzEsC0ecMAgojhyNJs/QQYnnkMHBD7UuEzwNElI5oFMo/Gpz
            QuDsMNHXOBUK8zSSoSExgHqujz7R282NMAtQxKkXN9STZEUTnvNKv1jaZkDJOAR4
            0XspSeUe/h15MXzN3ieWJfMwkqPyI8ADlPxZtSKKWK4q8qzErVNFIHBf1/cS9sU4
            NzGJabPExFGffPiYfpZ9S46kJHt5aM9kU6LFGSGBrRMZOSR4m9bIjinvIEmf2GO1
            ttcsPVSQEEIZzxFtyGuNXcHmZNl5mmX5b7KaWUDsPCWbijQfEH0nItkqNQuqX6RJ
            duxfhjLForu7z+puySB/C/4sZwtnaEAssDRcVYTPluvlTd3XLGy9zrMbGP8imVdR
            ONLhCJT5Smh2vn5np04xAEoJ0qdUPSh8DlpWIf36Qmkcov1GOBS56L87uv/Y8oc4
            fiHITpEGdnvLSRTtV4NLbeHznekt58TTkiB9EiiBVJXCmkx0FKEuC9QauSTU3P7W
            5vKhpJEfyYYGW5yMe+sYReac5+CFD25HjCcLxmbIX8B19QFWdj407h99dyj3NAKB
            8m5jHx0FLMtkPV8QBqV40G3i8E4a+sTnN8S0OIwJKKNHYCdvlOhM6lGzmFlU1kjD
            qnFIVc8PTVyZ96ZafgV7cVwN348kiqEBtIRuZhSGs8IeB4hVhjGhunjfpMdTH3ed
            T2uyIQvq2HjC5AtISKDLHooF5kgUi7PPh8W3WRWoNtpcW1fqX9rSpxNYmYWAO2VB
            JvTZvVTCYncsRpisAbmjQeUWxLzZKIPHMV9/GGE5sOk0GQPFV75B3G2ghNWIZqes
            yRQM0dQ0tpkS57LrSkc8+vbSXgGBak7QOs56lhHO+L89BlMs52Z6wRLuBbJGO3go
            klPzwwE6JNBKYZFv1A7WtELwijOX2yTNi5gn/W5J5AYTW3zb41cVWIIQ1shktpgu
            n1vU6H3gQncZe5qFLlH2OcM=
            =j+Uq
            -----END PGP MESSAGE-----
        fp: E940DD1F01DE41AC266825F72E962083AFA12A4D
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData$))
    version: 3.6.1
