apiVersion: v1
kind: ConfigMap
metadata:
    name: authelia-config
    namespace: authelia
data:
    configuration.yml: ENC[AES256_GCM,data:iCMH22ONQMMEKsk0bZwRDZTRt6Va0DM1zbpMFvyenmmzTnbxxyeNejqlg24x1ORCE7G9TFE0Da/hO3WCt/5VJiAFUVLHOV8gPB6uUsl8Ok5hxswVYA42iv+PDpMQgz1xwQ/9OmCUMKrczKg8Q/y7x2aijxt/7VsZvwKyVtfFM3FE9g71PKzBbe1gKxQ02iZZjIURcR7F/hoZSOC3xgGDw5sft6hv3IhXIfstDejrlF7LhS6xGR27t/bxLXqodnrYZwPe+qN5zw44wrC5AGfKiF9sx0dzumWyCMslB82K8otVV9oPzgLnakGtEiMIQGJeEr3jhQczYmz1KVRx3GHYFx8Z232KEjAICR8gcm5Am2LLJVLXkgyuECt+xRYFjbWkNCQd4gFF1zOsgXgS9GBo25Jqfu6rTPHXxm5Ebn96YSR1/9k24vZbxoqK6VGM1gCoyLDV1ngyfaoL3jlltA0YeMMofP/nwJOlAhgTh30xnl+sKP6IQx7yyrvodtHP6+tIxaxI/FdGRZg8Ujl4UVzNFiI9oIr+IpKzGdmnLY2ZEmkvftl19BgwQancJOJfhKu5tlru0cnNoJLitaRbOU0iZuSKUXhQ5I0VSKrAxNsls2mWOdLdMkKh+6cUPTvnoLkRcdjiZfLeT3esCBp5/Y7QCOJiAgAV+YO3g6xNpDbc9vt29hAu2YPwW0PofFmETlDILN3jrFw4ZAuX9tr+VujzHjRXs3XzMc5k7n8+V3ZXZon4tS2TcmNGhw+lUAxm/mGX3oDW4FTbGH0keNBtbK1qnuQ3HCYxtTDMcG9Rj3cGx+bvXyH2Skq8thG6lH0jFzrQhTi+/Fclpz6srrSe+1JhbQw2mLkoMeKpPDAYbIWvbyS95qyiy6r1fl81DIrZNA3cnkpdPLqMZM47hDiYVPEDUTguyxmKHcroBojcugerCPFyXCJb/91df5H1Fz041np5c4aLNH7OWSbzUb0OmQAuP+ALGNpYN1CGvQoAfizOZSggLqCxcoNrqctYe6DDIzdWo2gYPgQxbWDjAaguLP2tBQ97cSeKRyg0UZgqhfSJvkKNLqMmwE4lwFzqqTv+fjvsP+Iifxz7g3dQ2heT8XZvdHMYoDIDpEV8XWYf0P1KELCVdkMt0bqqilWettbK60PDbs3XMtsdefx1QKh31YaGvkAUp0TmGNO+gjQ74+qRNpgFaaO+guqIzHcR+s+2WSZ4yqQ/c3MOcK9Bbomq70c+hdAGBOKbpNFlYdEClAF5g8Oi8qk35JRYqHkervsygIz0eMLeyQXlqNpMkypG4Cacsq+cKWmEUGhZMO9WNkuu1LD0SFazmvbPZ+zgqSyuAAPu3FbRiV4ihT7RKFxg2YTd0MG3hNyp4SoiS2EiPxNje8AGylCRePkPpfRqJaosoPHcAMsyY30Avs+ZOVXHcVi2x8O196yHkUPh2oqPhCgOgdQB7gIf8PehXllRhAGGm1Uj5Ve1gMc7mE063hieL5wySrrCB3Gcy2U2U0acWrLrJJe/jyumu6pHi0ZErtZWwH8EmP9g1oH0o8WrVQdYLTY13w8n0G9Dls8f7Vfe/v4bqgf4CdpcpfeADhCUZPHDlnQCnW0ogwbaG8s+RPBlue/UQ2k7XNtwFWdBZfo5R2jefb3dW1PgGhJjvc8MD4pcrYATjygfR3YKMjIHuTg3gRmmvmKGCJZ3lOgM6t5WfF13el+/FdjgOTDHVbW1NkKpEpc/WciKn+h/+vhgniAFzYNWVz1FajffYqEzUmk7GODrZlVn+MOVXtr4/1odfzDDZ4su/RjgEr8+U20buGvsvCx33yauatGn0F9TsKOHevA0+JLNKg3XATiViLtDEhVJp/uAxeh5u4ff1nN6CI8/zA2eu/Zu1U21d79BFPt9kK3WqAOC/ZHxzOfPSgMC8B7ucEMN/ulfImO48PF4SpxfY0nj6RBnq7ompT5wq3XnQeQiwF9tynvRHz9fbr7OOITmyYzf+Yj4UWicRljDVqGCE1xl4ss7jinBkSrrIyL7Evd8vZO/I3kT1p+Umgs91cjcSht6yt6GVWQ4kc/EUSrkg2GFHCSIvg8lLSaQig==,iv:8wsj6Vwh1ZlxGz1wFaE9cpnUvYko+ptQislE5fndbi0=,tag:/xRsqmrbRe6Uf3/1vky5QQ==,type:str]
    users_database.yml: ENC[AES256_GCM,data:R69qGaew6sTr+GhIJlvRpkdhEI7FAjhv2O60W4u7h5zOomeFELC9tg8Zl9ntpAU7TFoMaMhL6nD52xrik/dAKfyHVEtpmJD2NVuOYhsx2Wc2ZJxDGczVpWu+QTIKgttKFTgLIQpbERjuLtBfbukwdm1STStEOyp2Qm+78Xo420BGqaz2cLhVBqwDRL5gA3m+sR1sXHIr2XVh2S3V+4oV+fFr7VeNRHCBClKDQ1DfjpZ344+jBUw1okxDiwgfSIvZ512+u3YBvcD3GGc0Pe2isPnt4MZGCUaq1TSVz6w17+7kvxpmc3Tg9aL5/sJ+JW7fzCZtx4PCdI2EGGi9EfQMvkGv1wWyvQJvt/DHqfprtXqHPprxxUYfXjJBQI6zlbZ3clcNg05UvN0WioGIZ460mQ0jjxDFmwlfE/VRYyyI2LPpjYazqX/gMfXGqdgnz3T5n5nMPvk+m2ELLsaZ3MBUlkWcz+cuR+N5V3AGn1jEefA0abcbMv6CUtJIzQckBoE50MnA7+QYwyzm2DVgXWj+/+5pAm3BbTnB1cy8vNBVylbY3A0NGeoGF1wgTLhoUpz0qPGgAnuSKiZy5bJkgWLbA88RiGL6dSwDN3zSNZgRq8uAQ+lrWYwJobacU73u6Og=,iv:ctnnrxdcl/Rfihly2R/4KdxgDcjlpPF7raCPHMtizZ8=,tag:KKmrG9xrdz2KtfsHTZ1Tag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-04-03T00:27:36Z'
    mac: ENC[AES256_GCM,data:qpZprOL5U4zPKNXUjUGGeLhjaGydZmhaiuiQMIy7EJSIKME3MZENBoj5FbDXFOS5PwjnyefVAabisTEb7dHRBiMvo1w6k1aEEtMe4Xh2R2TaedmoJeVm61bhna/ie/xGFsI7HQ7YP3tbURTkXKn1jEz8f9zO0805+lZCmuywVzw=,iv:HeeQ8vct03DNvX9cx89wrR80J22Sqpr3etHEVKpvSCo=,tag:x80vJjaJBHbjwXTlkaYMHw==,type:str]
    pgp:
    -   created_at: '2021-03-20T20:10:27Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQMOA4x50yY5upzjEAv/ZgJisC3UQDUCOpL0Ui+dinnRTDhtkXRmVTbC7ORXAmOU
            rbANQylqI2lGOt+kX2v/PUSP/0DSSzxnrhxl/+iADRs1sfmR1Vg1cQYc4JlGuVvG
            AeX+siGsdh94Ekc6Xhx6v8m8UV4IH5l2ACDFnqGdQI9ETVtmd4SezTnnL25irYfn
            28/CVJd0GY2CKybcWzEsC0ecMAgojhyNJs/QQYnnkMHBD7UuEzwNElI5oFMo/Gpz
            QuDsMNHXOBUK8zSSoSExgHqujz7R282NMAtQxKkXN9STZEUTnvNKv1jaZkDJOAR4
            0XspSeUe/h15MXzN3ieWJfMwkqPyI8ADlPxZtSKKWK4q8qzErVNFIHBf1/cS9sU4
            NzGJabPExFGffPiYfpZ9S46kJHt5aM9kU6LFGSGBrRMZOSR4m9bIjinvIEmf2GO1
            ttcsPVSQEEIZzxFtyGuNXcHmZNl5mmX5b7KaWUDsPCWbijQfEH0nItkqNQuqX6RJ
            duxfhjLForu7z+puySB/C/4sZwtnaEAssDRcVYTPluvlTd3XLGy9zrMbGP8imVdR
            ONLhCJT5Smh2vn5np04xAEoJ0qdUPSh8DlpWIf36Qmkcov1GOBS56L87uv/Y8oc4
            fiHITpEGdnvLSRTtV4NLbeHznekt58TTkiB9EiiBVJXCmkx0FKEuC9QauSTU3P7W
            5vKhpJEfyYYGW5yMe+sYReac5+CFD25HjCcLxmbIX8B19QFWdj407h99dyj3NAKB
            8m5jHx0FLMtkPV8QBqV40G3i8E4a+sTnN8S0OIwJKKNHYCdvlOhM6lGzmFlU1kjD
            qnFIVc8PTVyZ96ZafgV7cVwN348kiqEBtIRuZhSGs8IeB4hVhjGhunjfpMdTH3ed
            T2uyIQvq2HjC5AtISKDLHooF5kgUi7PPh8W3WRWoNtpcW1fqX9rSpxNYmYWAO2VB
            JvTZvVTCYncsRpisAbmjQeUWxLzZKIPHMV9/GGE5sOk0GQPFV75B3G2ghNWIZqes
            yRQM0dQ0tpkS57LrSkc8+vbSXgGBak7QOs56lhHO+L89BlMs52Z6wRLuBbJGO3go
            klPzwwE6JNBKYZFv1A7WtELwijOX2yTNi5gn/W5J5AYTW3zb41cVWIIQ1shktpgu
            n1vU6H3gQncZe5qFLlH2OcM=
            =j+Uq
            -----END PGP MESSAGE-----
        fp: E940DD1F01DE41AC266825F72E962083AFA12A4D
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData$))
    version: 3.6.1
