# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/daemonset-apps-v1.json

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: minilb-dns
spec:
  template:
    spec:
      priorityClassName: system-node-critical
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - operator: Exists
          effect: NoSchedule
      serviceAccountName: minilb
      containers:
        - name: minilb
          image: ghcr.io/vaskozl/minilb:0.2.2@sha256:ce3ec5bd2786e770c96d5da752151a36968c99a648922764885cf3052ad00037
          ports:
            - containerPort: 53
              hostPort: 5353
              name: dns
              protocol: UDP
            - containerPort: 8080
              name: healthz
          readinessProbe: &probe
            httpGet:
              path: /healthz
              port: healthz
          livenessProbe: *probe
          resources:
            requests:
              cpu: "15m"
              memory: "10Mi"
