# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/daemonset-apps-v1.json

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: minilb-dns
spec:
  template:
    spec:
      priorityClassName: system-node-critical
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - operator: Exists
          effect: NoSchedule
      serviceAccountName: minilb
      containers:
        - name: minilb
          image: ghcr.io/vaskozl/minilb:0.2.2@sha256:a43374369c939756f3205b33f28a240bd340dd6784b5a8fb3523e8dd0c10f3e6
          ports:
            - containerPort: 53
              hostPort: 5353
              name: dns
              protocol: UDP
            - containerPort: 8080
              name: healthz
          readinessProbe: &probe
            httpGet:
              path: /healthz
              port: healthz
          livenessProbe: *probe
          resources:
            requests:
              cpu: "15m"
              memory: "10Mi"
