apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: lmstudio
  namespace: agentgateway
spec:
  ai:
    provider:
      openai:
        model: "qwen3.5-35b-a3b"
      host: 192.168.1.179
      port: 1234
      path: "/v1/chat/completions"
  policies:
    ai:
      modelAliases:
        qwen3.5-9b: qwen3.5-35b-a3b
