apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayParameters
metadata:
  name: agw-params
spec:
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      memory: 256Mi
  deployment:
    spec:
      replicas: 2
      template:
        spec:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: ScheduleAnyway
              labelSelector:
                matchLabels:
                  gateway.networking.k8s.io/gateway-class-name: agentgateway
  service:
    spec:
      type: LoadBalancer
      loadBalancerClass: minilb
