---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: default
spec:
  chart:
    spec:
      chart: qbittorrent
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
      version: 7.1.1
  interval: 1h
  values:
    image:
      repository: k8sathome/qbittorrent
      tag: v4.3.1
    env:
      TZ: "Europe/London"
    service:
      additionalServices:
      - enabled: true
        nameSuffix: bittorrent
        type: LoadBalancer
        loadBalancerIP: 192.168.1.19
        annotations:
          metallb.universe.tf/allow-shared-ip: qbittorrent
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "internal"
        nginx.ingress.kubernetes.io/auth-url: "https://gate.sko.ai/api/verify"
        nginx.ingress.kubernetes.io/auth-signin: "https://gate.sko.ai/"
      hosts:
        - host: "qb.sko.ai"
          paths:
          - path: /
            pathType: Prefix
      tls:
      - hosts:
        - "qb.sko.ai"
        secretName: ingress-cert-qbittorrent
    persistence:
      config:
        enabled: true
        storageClass: "nfs-client"
        size: 2Gi
      downloads:
        enabled: false
    additionalVolumeMounts:
    - name: media
      mountPath: "/media"
    additionalVolumes:
    - name: media
      persistentVolumeClaim:
        claimName: nfs-media-pvc
    resources:
      requests:
        memory: 250Mi
        #cpu: 25m
      limits:
        memory: 6000Mi
