# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dossier
resources:
  - _namespace.yaml
  - hr.yaml
  - regcred.enc.yaml
  - oidc-secret.enc.yaml
  - minio-secret.enc.yaml
  - minio-root-secret.enc.yaml
  - vmservicescrape.yaml
  - ../common/redis
components:
  - ../common
  - ../common/redis/ephemeral
configMapGenerator:
  - name: seed
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
    files:
      - claimpolicies.yaml=config/claimpolicies.yaml
      - orgs.yaml=config/orgs.yaml
      - providers.yaml=config/providers.yaml
      - users.yaml=config/users.yaml
configurations:
  - kustomizeconfig.yaml
