# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: dossier
type: Opaque
stringData:
  DOSSIER_S3_ACCESS_KEY: ENC[AES256_GCM,data:N5Q/i3JS6UKXiQiqdxpxxEMLOdoR6tF3,iv:UPn0eH9xa//uyBpfg8GDDP22y7oNfr5T6hftj8GpHAs=,tag:eksNTzeAYTtqngTogzEWvw==,type:str]
  DOSSIER_S3_SECRET_KEY: ENC[AES256_GCM,data:lpT/duyJN0VxAwXxx+9fPiEseyC+svwQAF8mMRM/Ihrvs5ORXNFl5MfEsu4QOSow,iv:Hbsqjo+Ljy65RCGc9vbA518a0os+WtWjMsIf7LVLQtc=,tag:cV5u50VTfHR3sKsvDieTdg==,type:str]
sops:
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData$))
  lastmodified: "2026-09-02T12:43:35Z"
  mac: ENC[AES256_GCM,data:dwzOn6TfqelWk0lqHvxgBB0B5mobXQ8T73n1zxTASQY1Bp70F7B3F/uHdm8KD5OJVDkkk0G+nkB+qb8cklKBXiw1NeVw7GvBXH5Dcv984u2gx8Z7er96uqqIGWGcZGII67i8wGnlKci25WBMXAwfFLi9KIs9bROaa5E7BxVohss=,iv:KNEX81hI/Aqg4FSTlglC/tTeHJTKmyNofH9KVGwLyys=,tag:4V63Duk/6iTRAhmvgEhCXg==,type:str]
  pgp:
    - created_at: "2026-09-02T12:43:35Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQMOA4x50yY5upzjEAv+IrXXld9ebGpSvjhecOiizainHSJrC/4Y8gRJbmUfPH4e
        834CzPKbSf9G3LT3/4pqAptr4LzNhkUuigTW5nUP35xWoWE1YR0crDk0vsrITcI9
        2Csut6QSWfW1Wsy1ztzN/vGswsViL/+7QWh8eQ6Mnt3rroAhovLyOUaMA4JQDGiS
        Ctc59xUnp5MBwfyOyamOtrU3NcDM3PgfTv5RoD7lkLPY+ev3awhkOpaSiDSVFTUd
        0SU9LqJchzonRrh0Ou1gCe0LXSSUKnu6kICXAifwT+pD95ve0HDLEBqgx8UDRVnn
        5Omm/5E/nmWs7x588fgJi9DTFiweasa49Ur3812OHlXEjlY+xjhcYsiAl6orRjPu
        Z8Iuqn+fj6H04RgV2xibYOw/yFcJOhB7tThFKjMT4qmojgnChMZxBIZXz+0iVSpr
        pza3imY/keRH4HNbg2w7vLBFFaE6Mk5CD110UbKiu2Xyetl0cT7Lc20hyMSU7gSo
        rd15waJ/ZZt9/GE9ippeDACaOD7/SCxAMbNVBlfd+Kadnq8WoEO5uADvCy5aXo8D
        CAGPwrueyNNX23iXs8Zi9N1TRidwA7PAYbqs3G+FrvOyxeT6+Is7uLb/BTkdmZD5
        /LHGpgvbU0fyIAT95ta7w7CE8BkNeih/sy3tf4YY7ZqiZf3Bx+pqQIhLtMd8Mq7j
        ugJ6WeA5hewyEEWMcHrzWZwSyPtCBh2cGd4qSGRQch7LfbEYRcQVCVZui2YWEdHu
        qL9voTmDvCnBsFrrU9jy1pwjsVrNqOgAECgPo8uC32oK+RebNdqEwiYAoUz16Xh8
        FXuh5jrvJGLTKa57W4Sna2SixnaIoDQ8LC0gfJtQgabDzMBSunK5rtW7nw1sZ66G
        8wQQD/4sZcAcqE9ay0tFG3BNF+mgnMamu0TSeFNjKZE/OtLNU1D4WsH0LU1ZC5qY
        g0bcIe15P+yntd9ToixTMDoR5WbM7B0QBgY0SwfCUJzjdRgo3DJGD+7BL/BTjdPO
        ftzdUr4PfFyGBGRYGOOhoh/SXgHw5pmTpOKd6GJ3j8BroWMFcIymtrWAofdH0VHm
        a9Vw/wNlfIXw6i+gOOkbi8bbePapQvSBHOP2UYuFif4+lUKEVOJIWpjz2Yde2dMr
        DBg51u1H/U4kBMhn1GAEvSI=
        =heTr
        -----END PGP MESSAGE-----
      fp: E940DD1F01DE41AC266825F72E962083AFA12A4D
  version: 3.13.3
