# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: dossier
type: Opaque
stringData:
  DOSSIER_S3_ACCESS_KEY: ENC[AES256_GCM,data:qgVrjSSdOg==,iv:VI3AdcRxzMMixRHhUcun456o/Cdhp6lyDrgGNeIyu1E=,tag:F6cKbX+bcgL6h69uD6V9fQ==,type:str]
  DOSSIER_S3_SECRET_KEY: ENC[AES256_GCM,data:Euh/XN2DQF7CtE2+2VV/RtxQFV+kkDsKApCTezB4RntU+CbKbJGwSYRrOvMzRWKG,iv:85JFX06OW1CIVmxioZdBPMSWR6tc9rlTPRCPoNXeBCs=,tag:pu+cdpcpy+wAG9g3+/EXFA==,type:str]
sops:
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData$))
  lastmodified: "2026-09-02T14:58:24Z"
  mac: ENC[AES256_GCM,data:vZPEsT0gWnL0jl/ml4HrMEYi6cetVEyN2x7tbv1Q7ycfPpkFd/1bBGtZzBduLVE3yYl8mNX/k9t+h348nBTrUwVK/Kaal+j4D+8UNlcZjZtsPnbb6SBqt2fv59G9MCmgh6Y4MhG+Bnu5s3limSAfQYdlerJwvTt5BG9L0CWfVTw=,iv:JPuQ7onE+rpaDn5RS74i6H/10GTSXSdrNxQ5IHwmHpQ=,tag:1do+aj4fTQn4lRZEkrsOqw==,type:str]
  pgp:
    - created_at: "2026-09-02T14:58:24Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQMOA4x50yY5upzjEAv/eHsOCBLdwvCjnIa/2Ig93ZH0Phd0noJyNL/sM4PQ0ZST
        wCU+ysMpHysyu/L2sBySYgEVitJKKH0Zwt/uIOlPsKDC4WbjxlButMbonADh0OZi
        bgvSVw4dcf/apeuJaCMoESGxSIdqa8UaAuudmqfC1sIdJxxLGpYaDFudM/lS3fTZ
        9KHymUnV09/V5IWYD9I2q8FjcI/LPIkQLUxkjqPbDAcVas0MiD1ctWnhhhonnamC
        3nhT33WqTLaLwk5VMQ9cyYClMhatkmlw5KLkXyidzqxCT+btbHJYnHU8kKH01+1O
        Np6hoEP///b0EOhIKAMS9MQueS8CV7HjIS5k9SSeuzp16rDKu++AVgjKULgHH9oi
        ATSoAOaSOmIGKrMQaIXa+202RCpktCE/iIePeNb3O/i7gMim3oM4+SDaP1KkTWZs
        zkvijwluGtRWzg3SjQh8k8c/VIidQO7kfpRO9//FPUSUYieWHK9VxsiP00eRx1yz
        BKEQAhZJ8bctLzHND4ntC/0TKmRrD/pN2aOHKvxM48cRP4AIOg8cNZYmNWTfdPKS
        dHNwJleIzSv30NIQI37HauqzPeL5UgBOjxjqagoCVjYDjGlTbO8PPXYgXq8k7ch+
        G4NtOKiKpPCUH2Zy3MGAp9Daa6HdNjISlQ21CyR1nk/lJmsERQtFWTVRywKfM/mB
        hjtqpgKkNqqN0qPQHWd3eZvFeVvbKK09eec8t0EtARSm3jRbPHAjwMRuXCJIAVvI
        qtPjTZBqSjVzmO9Cai8IujQ2WUQ+KmszMtvVJvguWlBVcF9Nf/TsDju/CD9U3u4u
        Cht/+CfAorDilVI5ZxTKQjWJ8IRtJbIPFDoaJlKy5kHpMgZ8LYIAv3GAColpDHJV
        7mZk2kfLp6bOUakFoH0S84QMTwhYn+fkaaBUxZ1y51kYAzStu+SDD0E5z5jfAJzc
        g6z5buqMgPg+FVR/GKx7ULsj2JT0Mq+Lct/MonxFUEncElje8Nt/RTOCyxxqaStR
        DxsFv4plYEhlHmyCBlpe7YXSXgFnkvS8MO7xyRyHFkEzlp8EyhFddf2WtSxtSpOz
        1Yc2ze1M7FUB2mOc4VDDzm2Wgvl0iUSr1I5rffOydZrdFv+Fe2ZYE9joycpkfayG
        tqSJAJZWDVWAFprod92zpLg=
        =GRec
        -----END PGP MESSAGE-----
      fp: E940DD1F01DE41AC266825F72E962083AFA12A4D
  version: 3.13.3
