# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: minio-root
  namespace: dossier
type: Opaque
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:7dJhS182RyDMNy94kJ3+f0607xgIEsSc,iv:mq09jeZzPv7q6sejYeDLe+apIC2lyUKZqxvjaTl0WJg=,tag:AXoPAlZ0p0tew+TnRPzW6g==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:8UYWAaNyRQWkOfXVvP9tVElOZeXYlut58H0XqMlhBgtmWOadCQoXdFWoyacHkov7,iv:QxEEZCfRtxLU2hv7qgbs2v7eztWVnVNmZ6G9LfuSOOc=,tag:1o1K5A8fv05VFRdX/e6oFg==,type:str]
sops:
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData$))
  lastmodified: "2026-09-02T14:58:24Z"
  mac: ENC[AES256_GCM,data:wL7nZCVZ3YDt8Rux3jM/HWV2BnfrsTesysLqV0sSY99hDQA6XfVTxNKN1Gvqdtjfe+L7uCGr7cGzQM1TfRKSSjASAV4ccfo8upmnziksLMJ9jjgJ8RagSpCYNcMfOApbqO8wJaFcA9MgU9CWkSIYGWrQqOmWliOjcyZtZZIlSPI=,iv:VvUF2mG1Jh1dI1rEKeF/s9hJp+PFnQrac6m6OiIxojg=,tag:mfpX0hBTKCEP1BxN6NpEEw==,type:str]
  pgp:
    - created_at: "2026-09-02T14:58:24Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQMOA4x50yY5upzjEAv9EbCGRZZL++VklM64sHqAsNsf4w3ctFtXHSH3B6fyTVMK
        w1mQKxoJHPwQ1edLKLnFViM2pJg8uIE+4hA+fHI8CDbt2uSwlnYCEWwM2y0/o2ht
        zSHUBwL/WWLvtKUO3m4p7PCYUfzr4MejwojJGec7fZ/dDOLY2JrWO+fmX+yjjA6x
        Gp11fzGozsT7a5RqnnBgmgWGqxrCXV0HaDQwWHi/KAtLgrv9w8o2jxFT1jjd0JAd
        12CgFLCRvZienXFAn9Ztrrq4bt20Fyw2/MkKu3ynev0k+QoLh5mV+yjb1BVuCwD+
        0jomzxIGN9IL5NE+QG33yglqcl19x4naJoZnIXMS+5xzdicl81tlvCiiu6NdXJrw
        TpThaVe54Y8mY8i+w0LqiFiUd8jidqgYYBqiNUek/6J2SJyvBK8K/8fN40P8P1H8
        BrmRMc6WVTVQf7auQVN/aUe0rDv1ieuMyl84bXeX5t1aAigi34pQYRtJdWuEsj7k
        DlxAklV6fxiF0SVcbYOKDACW8SyVYyErxuEKQOR2aDp9cvTIGOoSz9qVwgTFCkJw
        e325cZ0s4dJWMOMEdLGwwKzwJoozrc3ViZt4L5gSU55MSUaZ4SbJouTzEbHXOizd
        30iQyQOtdTnO3LQijMKiCPhcT0p/w4daOw+qf1ej94uPGGu4LPyLRfl93yR7UmRt
        wLFMmqVbi9ZKjI2ud2vuD9cafeihCApW0gL5RjzADPJ6vMMDMMGreFxBRhDJjxYF
        MsiNgjFGNXnECJVB0uF8t7LFKnNtqNJKGI8b6/MBSUJ/CVQxzEe7hMoM0gZoyumG
        S4upt2rsIYCfd6q8Fa2IR/BEqOsG//oE2+rXi1uDZHlIeh9UbB/tWgyWJY95z6YC
        wewbomx8h6WAABb7vadYnCB8XHhrPOakcqSCIwjOfHERqio6C6ux+3Z8RvjHg5oX
        c53+2yMr6aKWaRwyYJSLnlrx1nKBwcZuaBSU4g00zv39i99lxaM7cAP0GcTcW6mn
        4n6kupt/xLJqteee5zywzQ3SXgG8gBGgeU347VcijgxjsRoIOGTf0xLiIsKRtVGJ
        s64fr+Eez3vD8twvvS9KxoGAYTbwOs/dW9i3MG1Ip/aWKnsR1rfn0/Vj5BmPvIFh
        5Hm9qCCcfFm8PAKX6hkFZ48=
        =eRUC
        -----END PGP MESSAGE-----
      fp: E940DD1F01DE41AC266825F72E962083AFA12A4D
  version: 3.13.3
