# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: oidc
  namespace: dossier
type: Opaque
stringData:
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:QNwkdWFe7Gz06zo7vugCH6WA4kOOInWjigRveVNk+/Y=,iv:SiR9HdjbDd0iD7V7n8AhKlkse18mCFeXhy2bIKXjSuo=,tag:jRe/9QqTXYFNaKYrbL8Rhw==,type:str]
sops:
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData$))
  lastmodified: "2026-08-20T18:44:39Z"
  mac: ENC[AES256_GCM,data:W2u/IBhx5PJJZAMfcXHWHJklA1O6pbii5L/pe0PrRp3dPA4kpzwb1B5R7HShOJRRuxFptjkGDlHf6uGvj5Cxit5LYvfyMsxukYj+QEIv0hJO8rRm/EKt1rwebklQ7nQ7ywnsFQeBRg5IrpFjJd9CnulMy2yFRWVdEvHNRhnj09Y=,iv:UrY/vw4SolnqZH87xMHGQDIfNOKjyoiJbh8vuzNAndg=,tag:XvECM0bnjOW8nwm1WoyLVw==,type:str]
  pgp:
    - created_at: "2026-08-20T18:44:39Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQMOA4x50yY5upzjEAwAsFq3sXEkk9NjFLsSncNMqFcf7FzI/f0i76/2YIJERAp2
        YC6lkKE/tt9rhgkESJzptFZyvoomufF9lsPw+IRQvy2Maft2GSDYm94oEn8b2n8M
        AIEmEa1m0rMOvAgLI9VR6Z26jKSs5uledjRMOFMWFANjq7Uz2DpItAuK1EZuM2JQ
        EabZdfXVpDRgeKkzC/aj9SckZeQ3204NvnAHMtj/T4QmQ3u/1AWTZ3nNqo1DFQ/i
        qDznqf+4H0EDGHvC+aB5kTtsBmU94BHLTuq+pqcF84rBNlfyDdLrWC+htTFOw2z4
        dMcIJzZ3Ez05EoPYVNN9L7iWvSPToMJWSWouoTN+Ub6dz2YBQT9G5AeB+LjyVAMa
        bYDepoZlncb1Wbpju/1OmHWzYYB8rr/cc4rtr9qVxf4QMXlAw5/0bUbK/Qk1dTNv
        05j9r7G7jUjzv/jFuXE7BrhIYG6kZu3uSSrjfHU0RCN1X5ZQGs3x1dlXOHwPHx/A
        0Gw/RHYDUu0B97fdFjYSDACPPxOopr5+Kp0gCe/JW/D5rChpxmeGwi2CDMrd9hdG
        YmaDnQJYwe0v7zrdB16zTFb07+ebjLsdFZn5E6KlCaLCOPpH78u6SQ+NGLFHaXlT
        ewwaCJSonSk9WOLkwbclinxSbA7Xb8t/ehkN2iv2OsqCgvMLw9AwMe0BABZKJtL/
        gFCOJW4eVGt9owjp9WKThtfFnnrPGH9lS8K0mBFmuMH7L74VHAJUu/F+G+TA0s1O
        lfs8s3BYYVU3txgD4OYWGLMCl7FXw1uHUmCeD87wBieE4e7+3FMdwevchurSSTjM
        ++EpHTMaVOYLCb+CrUL58IZJNWMsP7/30QrdWnu9agRhwTdaUbO1yo1b86qB4ANG
        GDcUeIj5e3YkkOkzfQ71R0bIH8i4HbnwVNH6HYGIcDXml2Io/qkV0kIFMYdxn+rt
        saFJ8BhCiXELfxoKc1wt/aQHuslffKvbyczR+IHybQ6MPwwD/FWI+XC+5pvr6R+7
        N8xoUwP4NrG8WwkxIwix5fLSXAG2qzJResfAxfU17YFodiaUyQrOmQIyDiGmqm2m
        Wr7kUHdtfor2OqoOVuK+gSFEdtmJQhUjhawCuhIxjXnhr8H72bXoXpSa+c/XB62S
        LPmi8/7Kpl+yWxL1L7NG
        =eWFf
        -----END PGP MESSAGE-----
      fp: E940DD1F01DE41AC266825F72E962083AFA12A4D
  version: 3.13.2
