version: '3'
services:
  s3:
    image: ghcr.io/vaskozl/minio:0.20260410@sha256:dce20fc4f2dfd9efbc42de7398f0465ff574fd663ccb276de2c088ee4875472c
    command: server /data --console-address ":9001"
    restart: unless-stopped
    user: 1026:100
    env_file:
      - minio.enc.env
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /volume3/docker/minio/data:/data
