version: '3'
services:
  s3:
    image: ghcr.io/vaskozl/minio:0.20260410@sha256:3326a8be0bd0aef983975d208e34ae83e7bbbfc9f329c6245cc0799181b96aa6
    command: server /data --console-address ":9001"
    restart: unless-stopped
    user: 1026:100
    env_file:
      - minio.enc.env
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /volume3/docker/minio/data:/data
