version: '3'
services:
  s3:
    image: ghcr.io/vaskozl/minio:0.20260520@sha256:41022461331621f1ef6cf420baccc57cf09341e0698ce68b1ae71b47b63e7a19
    command: server /data --console-address ":9001"
    restart: unless-stopped
    user: 1026:100
    env_file:
      - minio.enc.env
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /volume3/docker/minio/data:/data
