version: '3'
services:
  node-exporter:
    image: ghcr.io/vaskozl/prometheus-node-exporter:1.11.1@sha256:d20d737b2d1d7818abb7e62bd69406c8be13f980c35efdfeb954eb4bc5057a85
    container_name: node-exporter
    network_mode: host
    volumes:
      - /:/host:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro
      - /run/udev/data:/host/root/run/udev/data:ro
    command:
      - --web.listen-address=0.0.0.0:9100
      - --path.rootfs=/host/root
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.udev.data=/host/root/run/udev/data
    restart: unless-stopped
