version: '3'
services:
  node-exporter:
    image: ghcr.io/vaskozl/prometheus-node-exporter:1.11.1@sha256:b737b3f6752093cc02f0b98b37bd5c8e25fc70132724fa95e95709b73c7b063a
    container_name: node-exporter
    network_mode: host
    volumes:
      - /:/host:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro
      - /run/udev/data:/host/root/run/udev/data:ro
    command:
      - --web.listen-address=0.0.0.0:9100
      - --path.rootfs=/host/root
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.udev.data=/host/root/run/udev/data
    restart: unless-stopped
