version: '3'
services:
  node-exporter:
    image: ghcr.io/vaskozl/prometheus-node-exporter:1.11.1@sha256:ebcc7ac3e402b0916ec88ab5305c74b80809a85a2c93dae7a1f8e4330e0f3e01
    container_name: node-exporter
    network_mode: host
    volumes:
      - /:/host:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro
      - /run/udev/data:/host/root/run/udev/data:ro
    command:
      - --web.listen-address=0.0.0.0:9100
      - --path.rootfs=/host/root
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.udev.data=/host/root/run/udev/data
    restart: unless-stopped
