version: '3'
services:
  restic:
    image: ghcr.io/vaskozl/rest-server:0.14.0@sha256:e51b266f482c99875b164370f207eb53cc285db9c001137a7a5c4192320b57ce
    container_name: restic
    restart: unless-stopped
    network_mode: host
    user: "568:568"
    entrypoint: rest-server
    command: --listen :8000 --path /data --private-repos
    volumes:
      - /volume3/docker/restic/data:/data
