version: '3'
services:
  restic:
    image: ghcr.io/vaskozl/rest-server:0.14.0@sha256:c801bea11437e01cf7fb8cf62123e4ebdca8833fb78e27a72dd4ad0d74a1063e
    container_name: restic
    restart: unless-stopped
    network_mode: host
    user: "568:568"
    entrypoint: rest-server
    command: --listen :8000 --path /data --private-repos
    volumes:
      - /volume3/docker/restic/data:/data
