version: '3'
services:
  syncthing:
    image: ghcr.io/vaskozl/syncthing:2.1.1@sha256:c8d0e573a419e80f0247ec7b1f3d726698d461f2070777cef7025b1b5c3de8ac
    container_name: syncthing
    restart: unless-stopped
    network_mode: host
    user: "568:568"
    environment:
      - HOME=/var/syncthing
      - STGUIADDRESS=0.0.0.0:8384
    volumes:
      - /volume3/syncthing/data:/var/syncthing
      - /volume3/photo:/volume3/photo:ro
      - /volume3/k8s-volumes/vaultwarden-data-vaultwarden-0-pvc-1fc48917-f0c2-4a0f-8667-80cf47da1dc9:/volume3/vaultwarden:ro
    cpu_shares: 16
    mem_limit: 2G
