# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/cronjob-batch-v1.json
apiVersion: batch/v1
kind: CronJob
metadata:
  name: recyclarr
  namespace: media
  labels:
    app: recyclarr
spec:
  schedule: '@daily'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          automountServiceAccountToken: false
          restartPolicy: Never
          containers:
            - name: recyclarr-sonarr
              image: ghcr.io/recyclarr/recyclarr:8.7.3@sha256:9c6c74d52cfc6f740a5a3624aa83867e171bb70b90453ddb7a4048b8c80445f9
              imagePullPolicy: IfNotPresent
              command:
                - /app/recyclarr/recyclarr
              args:
                - sync
                - sonarr
              volumeMounts:
                - name: config
                  mountPath: /config/recyclarr.yml
                  subPath: recyclarr.yml
                  readOnly: true
            - name: recyclarr-radarr
              image: ghcr.io/recyclarr/recyclarr:8.7.3@sha256:9c6c74d52cfc6f740a5a3624aa83867e171bb70b90453ddb7a4048b8c80445f9
              imagePullPolicy: IfNotPresent
              command:
                - /app/recyclarr/recyclarr
              args:
                - sync
                - radarr
              volumeMounts:
                - name: config
                  mountPath: /config/recyclarr.yml
                  subPath: recyclarr.yml
                  readOnly: true
          volumes:
            - name: config
              secret:
                secretName: recyclarr-config
