# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/cronjob-batch-v1.json
apiVersion: batch/v1
kind: CronJob
metadata:
  name: recyclarr
  namespace: media
  labels:
    app: recyclarr
spec:
  schedule: '@daily'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          ttlSecondsAfterFinished: 1800
          automountServiceAccountToken: false
          restartPolicy: Never
          containers:
            - name: recyclarr-sonarr
              image: ghcr.io/recyclarr/recyclarr:8.6.0@sha256:3c38ceeb54438dd8327e4e65c9b48ba601a6d20fff833342d93c9b0bc4b1930b
              imagePullPolicy: IfNotPresent
              command:
                - /app/recyclarr/recyclarr
              args:
                - sync
                - sonarr
              volumeMounts:
                - name: config
                  mountPath: /config/recyclarr.yml
                  subPath: recyclarr.yml
                  readOnly: true
            - name: recyclarr-radarr
              image: ghcr.io/recyclarr/recyclarr:8.6.0@sha256:3c38ceeb54438dd8327e4e65c9b48ba601a6d20fff833342d93c9b0bc4b1930b
              imagePullPolicy: IfNotPresent
              command:
                - /app/recyclarr/recyclarr
              args:
                - sync
                - radarr
              volumeMounts:
                - name: config
                  mountPath: /config/recyclarr.yml
                  subPath: recyclarr.yml
                  readOnly: true
          volumes:
            - name: config
              secret:
                secretName: recyclarr-config
