# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/cronjob-batch-v1.json
apiVersion: batch/v1
kind: CronJob
metadata:
  name: any
spec:
  jobTemplate:
    spec:
      template:
        spec:
          shareProcessNamespace: true
          dnsConfig:
            options:
              - name: ndots
                value: "1"
