apiVersion: v1alpha1
kind: apkoimages
metadata:
  id: wolfi-base
spec:
  registries:
    - ghcr.io/vaskozl/wolfi-base
  tags:
    - latest
  config: ENC[AES256_GCM,data:fhn6MqW0E8bwEjN7hepqSxVfca0k+cry6wOW8HhyH0iuDqgP+Bu0fx/zNdom7j84NMHN89sSemdgpEZZ3VxAcO5uIZKHJPcYFH2WJj0cq9ZYt/U8zSKz7NL00IcaOGElgCv4ebtOZ6ikNFV0ATlmWJpN51Ay5iG+WbEk1tKcro/DrmLQB7F53wxoI7E9mwiPDrLbEIa2u9u/1Uvq/RDWNZL0FmvF2vYMzT0JadSLe2p18dZdfc4r5GizexYk+fPJQzByx2miEQE1g/Doiqf6EK8RVa2pUV3UbPo2J5zK+moc+3BwlvCYGsW/0BRxvsGdmWMUHeNMbNXGFVQDp2EdFOFdsgbhCdZDQNxD3mx5dRBBwwY4qGegSLcj/P62WdzfABmSZCitw/hxQ4jbH6ajXEPBRKdTtITYDvj/jMXzOGsHbLgLDLo1uSwVF784Ou8xe6A1rwVZ4NLmNksfNGpRjMO7jzXlLqhkoNqqRiqoYTR5ZLXUH34KQ4VZpOb9eOev7oKCXQoxwQyzrnPaz6pp9Jf10YJpKxv4eeqUFHLAsGUDrfd/sbQhnx6JLMR3sWBmSI1W3APG5QpHPdxGSHhBJTsTt+uYiEl2AyaZ5VRQxm1P6NJkxTC8xjJOk6yp8dsyAoTDoH5hxEqhQJiU21cew4B6FVu43VdTtBRWwwy+Mwk3Qg/H/oJYcsyVHZmhwSqFzeD9v9OJgtn+OxYd3R3O+GOJzoKKVUeaZFqLjPcdOrttKmGOruYnLP7z/ue3ea9cy7nyEAqH6o0IXJHylF1lVneqbrHuCnbKeQszUXzX1Xg/xYg114aJsPOcUp/lUc+ItHkYqzJbPIaouv7uc4Sc4RwfqTrPToESJvSN8m/oc7PokWGda6mUd0idyN0Ww/i1wiucg3D3/4tYSTmgIWPhJkr0UMWOOybuVH9HBM/omj2uDadgsjLd3a3BQIWDnOdnuy8DNj/uSvbBcVWzyARVXwrpBLWIb4duo1eVL2SnGXCmvVb5Jt8PaNRSB0LOnAu7q0DHfVU7ZBQIUy4uuPPlK+1WC9bQHoQn61xvF+lkekQrJVO9p2AybN+wfsXjlmSvoT8CNbmfR33PqyeFZtw0lXxYoSctJQgW2BXO,iv:tGsLju2qOO5BhDGCLhBzXSAyeGlXdi1iSb/ToSlJNRA=,tag:dRQ6G955uQHVGFqDZIrXcQ==,type:str]
sops:
  lastmodified: "2026-06-21T13:31:13Z"
  mac: ENC[AES256_GCM,data:PD3lfzbxLISI8FlMr0Og7hHrLx5mtnQ0+dG4TR8paCSlaWC8wfR8+JDxDdFMrLuRcLm/euNQi3yQhR/J/fAForIQedCjC7NZEvtQeIu7q8zP16Zu0Sne1BU9/WrjfoLgrPSPGbv3HpwBQWoYgGAf02MVt9PT8ZIWerF/QqoG7VM=,iv:ptJAqN/oqPNSqsTPw5I0ereuUk7gKpgszV6zy1ibyAM=,tag:JzU3NJz/t3GOtkB8pZtGhg==,type:str]
  pgp:
    - created_at: "2026-06-21T13:05:40Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQMOA4x50yY5upzjEAv/fcfj8Gz2P2la++N/lIdLR5mYMEuNCXu6vVK0RO+WVdlJ
        JK1aX8u9ptfrKpH6SBak3xLhjZs+UJUHqGZoOioBiuBi2pTJPkEo5h6hxdkXcZnt
        oKPVcXy4AG4wkH56RuozoAAfggY/VxaSWVzXOsfAl7sq+nqkySnb0GcUZawktWKL
        6oN9JYZZKARBZwB0EqAFrN0QQWjry5apTeXeope5YQEv8/nbUIqI/gq7yBbmPPf/
        TIYMlAEIcjuT+tNd7l6SKXiQYHKhcXZNBRZgBzssBrovr2RKRH0re/CH/X/4c/XV
        g2n9T+UCPPTBqtHZj3uo5oLiosOxZ6qwNDkicsgM+jNnlVFHabY7ekjEkv/Lhcs8
        Qb1ACUMIBVlB8KuYqoOpeOv+H7F67oZyA6GSuhzSru8NhdkDvlVsAz3/fDruDW1w
        MfbJeEdUkKEM6IKlEGzROVWTyclbosD1+ZekcS1dJBK+oHyiYApC4CjmhBkI9t7q
        LjpgsXJj4wVntvHuLCrpC/9LqMvBhrPR2o6+0InSCqVXr27PJyxe4MN91drYTGD9
        xbR25/t4aJdxK4rAFO2THeTAuM30PH+jkd/oygF2JIyS1EKPr4Rs27MJCPyfE2op
        6Cu9kl+/6AbNo6/Yx0sTY2D/p6sYlpOgBTDJXaI/zxC7HmcBR66wTTvO+Y3CKgNz
        xZFMnS+blrfZcNS3+wl0steaTkOJLXWHrXnoYWrXMtNJ5BaWMrpbnpQiMfqI1WlH
        J0u9LJ27q1SLyZHWR7OT6lXGmc4ObaNwb6iKRUDrT+m0Ivg196hejrtk0wm/W32G
        V1RAn0zwmbTbZitWq7khXN+QuYDczVCa3vYJtcSApUUbZPG2/39/RB6Z6cXQ3JcH
        57nCtUycdoeYeRn2hg/8aX+aoegiyIsabuMTNRd3LZD6St7yNs9bslHkeYFV9I2m
        AjNri8VpbFIV9PhtxHDYUCyR3Je7LVdNx57giZ+xI8Yz3xfuPuov6syGcXnPsYGU
        cIHX91ZEYYjyekVyhtuC3NbSXgHeV9cx/KVOTt+jV/xVfDn39LwaGiXmu7kkrWob
        t04t2Z+QI7tMSMk6cD9XdnjmCQLvWII9AChWpjbcU6bLI5tFUYEqX5Q5SijiREPg
        x4mJcRCK1Akt2l9imOx+sIQ=
        =gl0w
        -----END PGP MESSAGE-----
      fp: E940DD1F01DE41AC266825F72E962083AFA12A4D
  encrypted_regex: config
  version: 3.12.2
