apiVersion: v1alpha1
kind: branchhealths
spec:
  repo: https://gitlab.sko.ai/doudous/packages.git
  branch: main
  intervalSeconds: 1200
---
apiVersion: v1alpha1
kind: branchhealths
spec:
  repo: https://gitlab.sko.ai/doudous/home-infra.git
  branch: main
  intervalSeconds: 1200
---
apiVersion: v1alpha1
kind: branchhealths
spec:
  repo: https://gitlab.sko.ai/doudous/rekon.git
  branch: main
  intervalSeconds: 1200
