apiVersion: v1
kind: Service
metadata:
  name: omada
spec:
  ports:
  - protocol: TCP
    port: 8043
    targetPort: 8043
  selector:
    app: omada
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: omada
spec:
  selector:
    matchLabels:
      app: omada
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: omada
    spec:
      hostNetwork: true
      containers:
      - image: mbentley/omada-controller:4.2-arm64
        name: omada
        env:
        ports:
        - containerPort: 8043
          name: omada
        volumeMounts:
        - name: pv-omada
          mountPath: /opt/tplink/EAPController/data
      volumes:
      - name: pv-omada
        persistentVolumeClaim:
          claimName: omada
