kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: imagestore
  namespace: imagestore
  annotations:
    volume.beta.kubernetes.io/storage-class: "longhorn"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
