apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: imagestore
  labels:
    app: postgres
data:
  POSTGRES_DB: imagestore
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin123
  PGDATA: /var/lib/postgresql/data/pgdata
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: imagestore
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: imagestore
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: postgres
        image: postgres:13
        envFrom:
        - configMapRef:
            name: postgres-config
        ports:
        - containerPort: 5432
          name: postgresdb
        volumeMounts:
        - name: pv-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pv-data
        persistentVolumeClaim:
          claimName: postgres-pv-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: imagestore
  labels:
    app: postgres
spec:
  storageClassName: longhorn
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
