include:
 - project: doudous/ci-templates
   ref: main
   file: build.yaml

run:val:
  stage: test
  image: ghcr.io/vaskozl/kubeconform:0.7.0@sha256:d430886d3c5641dfd9733333573d28afe0ed688203cb52f23f3f8560f7f814d0
  script:
    - scripts/validate.sh
