include:
 - project: doudous/ci-templates
   ref: main
   file: build.yaml

run:val:
  stage: test
  image: ghcr.io/vaskozl/kubeconform:0.7.0@sha256:3755005e3553925465cac0dfe1b16b6c8163a01d74a958a03c98aa910e45139f
  script:
    - scripts/validate.sh
