include:
 - project: doudous/ci-templates
   ref: main
   file: build.yaml

run:val:
  stage: test
  image: ghcr.io/vaskozl/kubeconform:0.8.0@sha256:36203af69031fced1ac1c1b7489794f4358caca3c198527e7ae6e5dc2a40361e
  script:
    - scripts/validate.sh
