# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/cronjob-batch-v1.json

apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitlab-registry-garbage-collect
  namespace: gitlab
spec:
  schedule: "0 5 * * *" # Run at 5:00 AM every day
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: gitlab-registry-serviceaccount
          containers:
            - name: kubectl-exec
              image: ghcr.io/vaskozl/kubectl:1.35@sha256:d4edc398284c2bfdcc4e001dcbf32735d8e809abb26f812edac73da2dfe6c5a6
              command:
                - "kubectl"
                - "exec"
                - "deploy/gitlab-registry"
                - "--namespace=gitlab"
                - "--"
                - "registry"
                - "garbage-collect"
                - "--delete-untagged"
                - "/etc/docker/registry/config.yml"
          restartPolicy: OnFailure
