# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/cronjob-batch-v1.json

apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitlab-registry-garbage-collect
  namespace: gitlab
spec:
  schedule: "0 5 * * *" # Run at 5:00 AM every day
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: gitlab-registry-serviceaccount
          containers:
            - name: kubectl-exec
              image: ghcr.io/vaskozl/kubectl:1.35@sha256:94da9f6d25e58c7153890f46e8b9512219b2b4b505286041f9d86e315d6bedc2
              command:
                - "kubectl"
                - "exec"
                - "deploy/gitlab-registry"
                - "--namespace=gitlab"
                - "--"
                - "registry"
                - "garbage-collect"
                - "--delete-untagged"
                - "/etc/docker/registry/config.yml"
          restartPolicy: OnFailure
