apiVersion: v1
kind: Secret
metadata:
  name: moltis
stringData:
  BRAVE_API_KEY: ENC[AES256_GCM,data:yN2BPRluB53j7FYGGDB4clC5HELHy+aVmUPAkGXI7w==,iv:twx790SFvb82LNjRxElph9Xg2phaP5AX+RwEG87MvMs=,tag:MrplO5IhAzuGtPkGP+7+gw==,type:str]
sops:
  lastmodified: "2026-03-12T01:23:07Z"
  mac: ENC[AES256_GCM,data:K1XBQaakaB1/1Bg2mpAGdg45Y/2ohePAi7F19E5Xe2ipNO0/qtmkAH9u6Fpk4vLM+LMkYPKhHpuJOT1Z3diSYsIq8bxFnnDP31ptVKvCMvHxjf/GjMQ/zR9xoL1f2SD+6lgHc941hmYMJa6glRJ1n2q8MTwCUKATbFTwHgwlT7I=,iv:iMR3pyv4DlRJpDb2p8dGwC61XkqB1pJ2/YFOPOsjoFU=,tag:P+V9e+Ayan4cLu1OGEehqw==,type:str]
  pgp:
    - created_at: "2026-03-12T01:23:06Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQMOA4x50yY5upzjEAv+PEFsDtOmUY2pf2429s8atkSZfv8ZcxB/PR7G6GUKYTjp
        I4Fx+AdxplEZH8TGqVh8K3WL5LaDkHlAKATlxcTNqr9JWaU40H7TmjczbrHUHvKl
        Z5mvHhYaj+/id5dyXcIxGskYcjpvxK9qJp58vtOqaZGw0OGRnMcTEMgHsT+ITN3k
        d6ZYyjJL/UvJPtm5THpWe55bTkHqrDT75CQeGfrptTZu80jWaE/N3MWX8YC9OcWP
        vP86NYD6Qe+JNiA0WVXRDg43Q/RXKe82gODV1vRuHmrUU2RAF8IqYrAQZ9SwacAl
        2aPDvbWdEL84z3LzKjnpq1NsnPt6/gs7Uw5CI5J0ibxBQ8JP7Viwe22vX8/PY3do
        4WCH1r+ts5VfN7D98MsPme8y2Kn/lUdfDqb16hKE60CkNR+dQQjDZgq+/ryTQACz
        /uGwOdigH94I/9Ow2nnQmlcUG4+M9n4dHl3usAt2IuT+w3nrRxI+LhXIYYkJkiDA
        ogFUcukjBlQ4aIIo28W3C/4w/HmGmCKh5DKpMk4FETPzWkWYdxbnqMq1ZRjuz3fJ
        T1ol0SI2bqx7UmVHDmWyUwAD94ejpm7nQYkJdhbTgyfo9d9N6sJmYOSIK3kij4n0
        HFzDoQxXbUrLaOsgEaIHul+9gKm1ZtKI/hzOD+bBWuK6NV1ZsVrUvt88/P2NAsSL
        0KVeYE/u5RuzAO8M288GTynoyiddZRRp0KIsHTtKOgCtD+CV05u1/Y6OWks5kKgd
        OKKgO/GBEQds0mvlrfVZV2DuDA03FgXNlcOY1Ary91yFv7c++UThTRdwk9C9Zc6p
        4l8c8K5jWESF6KOL3oDwcyfGkqnRb6WLFqgkrKd4XUM/vjGnuLSCPPIDCV1M57Xz
        ap9oZSnc6Ov4XP3jJbAeXQkVy5YVU+VLhf9p2wWMMPcGbEWX3j8aBYzJnBwTo40u
        5zzd7aiCcaWGfBKUTTpTiGQXIQ7OriFTfcO8HOx6tw7UqKg47qbS7hj8+jN0fhZT
        cPtqhvl2+C0mLaiOw7eIoaDSXAG/SRrkSUnY3Qx0d2mWXHO11DTlczMtkeZmkc2a
        HQ77BBoyL8R9nCwrYtAuIDz7dSMAcXFdEatbu1Mw2Ri/tXhN0KK9iNIMDyZ9dBOW
        NTXwX7xccqyIsLcOhZjs
        =0hLd
        -----END PGP MESSAGE-----
      fp: E940DD1F01DE41AC266825F72E962083AFA12A4D
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData$))
  version: 3.12.1
