apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: index-photoprism
spec:
  schedule: "0 */1 * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
          - name: photoprism-index
            image: photoprism/photoprism-arm64:20201225
            imagePullPolicy: IfNotPresent
            args:
            - /photoprism/bin/photoprism
            - index
            volumeMounts:
            - mountPath: /photoprism/storage
              name: config
            - mountPath: /photoprism/originals
              name: originals
          volumes:
          - name: config
            persistentVolumeClaim:
              claimName: photoprism-pvc
          - name: originals
            persistentVolumeClaim:
              claimName: photos
          restartPolicy: OnFailure
