---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism
  namespace: default
spec:
  chart:
    spec:
      chart: photoprism
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
      version: 2.2.1
  interval: 1h
  values:
    env:
      PHOTOPRISM_SITE_URL: "https://p.sko.ai/"
      PHOTOPRISM_PUBLIC: true
      PHOTOPRISM_DEBUG: false
      PHOTOPRISM_THUMB_SIZE: 2048
    image:
      repository: "photoprism/photoprism-arm64"
      tag: "20201225"
    resources:
      requests:
        cpu: "1000m"
        memory: 1.5Gi
      limits:
        cpu: "3000m"
        memory: 2.0Gi
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "internal"
        nginx.ingress.kubernetes.io/auth-url: "https://gate.sko.ai/api/verify"
        nginx.ingress.kubernetes.io/auth-signin: "https://gate.sko.ai/"
      hosts:
      - host: "p.sko.ai"
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "p.sko.ai"
        secretName: ingress-cert-photoprism
    persistence:
      config:
        enabled: true
        existingClaim: photoprism-pvc
      originals:
        enabled: true
        existingClaim: photos
        readOnly: true
