kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: photoprism-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "longhorn"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
