kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: photoprism
  annotations:
    volume.beta.kubernetes.io/storage-class: "rook-cephfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 12Gi
