apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - _namespace.yaml
  - claude-cronjob.yaml
  - claude-pvc.yaml
configMapGenerator:
  - name: claude-md
    files:
      - CLAUDE.md
secretGenerator:
  - name: claude-env
    envs:
      - claude.enc.env
