# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    patch.sko.ai/app-template: common
  name: matcha
spec:
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 4.6.2
  interval: 24h
  values:
    controllers:
      matcha:
        type: statefulset
        containers:
          app:
            image:
              repository: ghcr.io/orangecadet/matcha
              tag: latest
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8000
                  initialDelaySeconds: 10
                  periodSeconds: 30
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8000
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  failureThreshold: 3
            resources:
              limits:
                cpu: 1000m
                memory: 500Mi
              requests:
                cpu: 500m
                memory: 200Mi
            env:
              data_dir: /app/database
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: false
        statefulset:
          volumeClaimTemplates:
            - name: database
              accessMode: "ReadWriteOnce"
              globalMounts:
              - path: /app/database
              size: 1Gi
    defaultPodOptions:
      imagePullSecrets:
        - name: regcred
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    persistence:
      database:
        existingClaim: database
        globalMounts:
          - path: /app/database
      tmp:
        type: emptyDir
    route:
      app:
        hostnames:
          - matcha.sko.ai
        parentRefs:
          - name: internal
            namespace: agentgateway
    service:
      app:
        controller: matcha
        ports:
          http:
            port: 8000
