# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agentgateway
resources:
  - _namespace.yaml
  - hr.yaml
  - oauth2-policy.yaml
  - sko-ai-tls.yaml
  - ../../netpols/allow-all-ingress
components:
  - ../../common
