# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/cronjob-batch-v1.json
apiVersion: batch/v1
kind: CronJob
metadata:
  name: common
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          shareProcessNamespace: true
          securityContext:
            fsGroup: 568
            runAsGroup: 568
            runAsNonRoot: true
            runAsUser: 568
            seccompProfile:
              type: RuntimeDefault
          restartPolicy: Never
          nodeSelector:
            kubernetes.io/arch: amd64
          containers:
            - name: qwen
              image: &image ghcr.io/vaskozl/qwen-code:0.13.0
              command: ["qwen", "--yolo", "--system-prompt='You are an autonomous agent that is awoken via a cron. Complete
                  your task indepedently.'"]
              resources:
                requests:
                  cpu: 500m
                  memory: 2500Mi
                limits:
                  memory: 2500Mi
              envFrom:
                - secretRef:
                    name: qwen-env
              volumeMounts:
                - name: qwen
                  mountPath: /home/nonroot
          volumes:
            - name: qwen
              persistentVolumeClaim:
                claimName: qwen-pvc
