# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/statefulset-apps-v1.json
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qwen
spec:
  serviceName: qwen
  template:
    spec:
      shareProcessNamespace: true
      securityContext:
        seccompProfile:
          type: Unconfined
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: qwen
          image: &image ghcr.io/vaskozl/qwen-code:0.13.1
          command: [ralph]
          resources:
            requests:
              cpu: 500m
              memory: 2500Mi
            limits:
              memory: 2500Mi
          envFrom:
            - secretRef:
                name: qwen-env
          volumeMounts:
            - name: qwen
              mountPath: /home/nonroot
            - name: ralph
              mountPath: /usr/local/bin/ralph
              subPath: ralph.sh
            - name: ralph
              mountPath: /etc/qwen/prompt.md
              subPath: prompt.md
            - name: settings
              mountPath: /home/nonroot/.qwen/settings.json
              subPath: settings.json
            - name: docker-socket
              mountPath: /var/run
        - name: dind
          image: cgr.dev/chainguard/docker-dind
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              memory: 8Gi
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run
      volumes:
        - name: qwen
          persistentVolumeClaim:
            claimName: qwen-pvc
        - name: ralph
          configMap:
            name: ralph-prompt
            defaultMode: 0555
        - name: settings
          configMap:
            name: qwen-settings
        - name: docker-socket
          emptyDir: {}
