# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/statefulset-apps-v1.json
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qwen
spec:
  serviceName: qwen
  hostUsers: false
  template:
    spec:
      shareProcessNamespace: true
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: qwen
          image: &image ghcr.io/vaskozl/qwen-code:0.13.1
          command: [ralph]
          securityContext:
            procMount: Unmasked
            seccompProfile:
              type: Unconfined
            allowPrivilegeEscalation: true
          resources:
            requests:
              cpu: 500m
              memory: 2500Mi
            limits:
              memory: 2500Mi
          envFrom:
            - secretRef:
                name: qwen-env
          volumeMounts:
            - name: qwen
              mountPath: /home/nonroot
            - name: ralph
              mountPath: /usr/local/bin/ralph
              subPath: ralph.sh
            - name: ralph
              mountPath: /etc/qwen/prompt.md
              subPath: prompt.md
      volumes:
        - name: qwen
          persistentVolumeClaim:
            claimName: qwen-pvc
        - name: ralph
          configMap:
            name: ralph-prompt
            defaultMode: 0555
