# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/cronjob-batch-v1.json
apiVersion: batch/v1
kind: CronJob
metadata:
  name: common
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          shareProcessNamespace: true
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 568
            runAsNonRoot: true
            runAsUser: 568
            seccompProfile:
              type: RuntimeDefault
          restartPolicy: Never
          nodeSelector:
            kubernetes.io/arch: amd64
          containers:
            - name: claude
              image: &image ghcr.io/vaskozl/claude:latest@sha256:e9b8528938422eb3e94a60395c179d58c948c90c4ddb1652bd87a2866f4af255
              command:
                - claude
                - -p
                - --verbose
                - --dangerously-skip-permissions
                - --output-format=stream-json
                - --include-partial-messages
              resources:
                requests:
                  cpu: 500m
                  memory: 2500Mi
                limits:
                  memory: 2500Mi
              envFrom:
                - secretRef:
                    name: claude-env
              volumeMounts:
                - name: claude
                  mountPath: /home/nonroot
          volumes:
            - name: claude
              persistentVolumeClaim:
                claimName: claude-pvc
