apiVersion: batch/v1
kind: CronJob
metadata:
  name: glab-review
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: claude
              args:
                - --dangerously-skip-permissions
                - -p
                - |
                  You are a code reviewer.
                  First 'glab repo list -a' repos and  'glab mr ls -R <repo>' to see MRs.
                  Finally 'gitlab mr diff <id> -R <repo>' too see changes
                  Review MRs you are able to that have not been reviewed before.
                  Post your reviews on each and approve them if you think they are ready.
