# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - sts.yaml
patches:
  - path: common.yaml
    target:
      kind: CronJob
labels:
  - pairs:
      app.kubernetes.io/name: claude
    includeSelectors: true
secretGenerator:
  - name: claude-env
    envs:
      - claude.enc.env
configMapGenerator:
  - name: ralph-prompt
    files:
      - prompt.md
      - ralph.sh
