# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - rbac.yaml
  - ../../gitlab/buildkit/buildkit-client-certs.yaml
  - lead
  - dev-sonnet
  - dev-opus
  - dx
patches:
  - path: common/sts.yaml
    target:
      kind: StatefulSet
labels:
  - pairs:
      app.kubernetes.io/name: claude
    includeSelectors: true
secretGenerator:
  - name: claude-env
    envs:
      - claude.enc.env
configMapGenerator:
  - name: ralph
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
    files:
      - prompt-common.md=prompts/prompt-common.md
      - prompt-dev.md=prompts/prompt-dev.md
      - prompt-lead.md=prompts/prompt-lead.md
      - prompt-dx.md=prompts/prompt-dx.md
      - ralph.pl=prompts/ralph.pl
