apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - glab-review.yaml
  - pvc.yaml
  - sts.yaml
patches:
  - path: common.yaml
    target:
      kind: CronJob
labels:
  - pairs:
      app.kubernetes.io/name: claude
    includeSelectors: true
secretGenerator:
  - name: claude-env
    envs:
      - claude.enc.env
