apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: claude
spec:
  serviceName: claude
  template:
    spec:
      shareProcessNamespace: true
      securityContext:
        fsGroup: 568
        runAsGroup: 568
        runAsNonRoot: true
        runAsUser: 568
        seccompProfile:
          type: RuntimeDefault
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: claude
          image: &image ghcr.io/vaskozl/pi-coding-agent:0.59.0@sha256:0f9f71bcc1b2d530095bb218bc2189c1147d7596b148a1a696e28340b3c848e3
          command: ["sleep", "inf"]
          resources:
            requests:
              cpu: 500m
              memory: 2500Mi
            limits:
              memory: 2500Mi
          envFrom:
            - secretRef:
                name: claude-env
          volumeMounts:
            - name: claude
              mountPath: /home/nonroot
      volumes:
        - name: claude
          persistentVolumeClaim:
            claimName: claude-pvc
