apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: claude
spec:
  serviceName: claude
  template:
    spec:
      securityContext:
        fsGroup: 568
        runAsGroup: 568
        runAsNonRoot: true
        runAsUser: 568
        seccompProfile:
          type: RuntimeDefault
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: claude
          image: ghcr.io/vaskozl/claude:2.1.76@sha256:27e8b9633b7b83c09f8b2247cafd7dd82a0bed92ed8908fca188dafbece0749b
          command: ["sleep", "inf"]
          env:
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/linuxbrew/.linuxbrew/bin
            - name: HOMEBREW_NO_AUTO_UPDATE
              value: "1"
          resources:
            requests:
              cpu: 500m
              memory: 2500Mi
            limits:
              memory: 2500Mi
          envFrom:
            - secretRef:
                name: claude-env
          volumeMounts:
            - name: claude
              mountPath: /home/nonroot
      volumes:
        - name: claude
          persistentVolumeClaim:
            claimName: claude-pvc
