apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: claude
spec:
  serviceName: claude
  template:
    spec:
      shareProcessNamespace: true
      securityContext:
        fsGroup: 568
        runAsGroup: 568
        runAsNonRoot: true
        runAsUser: 568
        seccompProfile:
          type: RuntimeDefault
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: claude
          image: &image ghcr.io/vaskozl/pi-coding-agent:0.59.0:sha256:d7e3f91b4171c84f3dc961a0a69763ac90bde2177f0878ce7b595a353fb56cbc
          command: ["sleep", "inf"]
          resources:
            requests:
              cpu: 500m
              memory: 2500Mi
            limits:
              memory: 2500Mi
          envFrom:
            - secretRef:
                name: claude-env
          volumeMounts:
            - name: claude
              mountPath: /home/nonroot
        - name: chromium
          image: *image
          command: ["xvfb-run", "-e", "/dev/stdout", "chromium"]
          args:
            - --remote-debugging-port=9222
            - --no-sandbox
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              memory: 1500Mi
      volumes:
        - name: claude
          persistentVolumeClaim:
            claimName: claude-pvc
