---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flood
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: flood
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
      interval: 30m
  values:
    controllerType: deployment
    image:
      repository: jesec/flood
      tag: 4.3.1
      pullPolicy: Always
    env:
      FLOOD_OPTION_RUNDIR: /data
      FLOOD_OPTION_AUTH: "none"
      FLOOD_OPTION_QBURL: "http://192.168.1.19:8080"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "internal"
        nginx.ingress.kubernetes.io/auth-url: "https://gate.sko.ai/api/verify"
        nginx.ingress.kubernetes.io/auth-signin: "https://gate.sko.ai/"
      hosts:
      - host: fl.sko.ai
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "fl.sko.ai"
        secretName: ingress-cert-flood
    persistence:
      data:
        enabled: true
        storageClass: "nfs-client"
        accessMode: ReadWriteOnce
        size: "1Gi"
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
  valuesFrom:
  - kind: Secret
    name: "flood-helm-values"
