apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: flood
    namespace: default
spec:
    interval: 5m
    chart:
        spec:
            chart: flood
            version: 2.4.0
            sourceRef:
                kind: HelmRepository
                name: k8s-at-home
            interval: 30m
    values:
        controllerType: deployment
        image:
            repository: jesec/flood
            tag: 4.4.1
            pullPolicy: Always
        env:
            FLOOD_OPTION_AUTH: none
            FLOOD_OPTION_RUNDIR: /data
            FLOOD_OPTION_QBURL: http://qbittorrent:8080
            FLOOD_OPTION_QBUSER: vsz
            FLOOD_OPTION_QBPASS: ENC[AES256_GCM,data:AYmrewD40Ktzib1sBqIrhw==,iv:9Fr1+fcD6Gp6Tfi4aNKiXXO5IwyEwkhTcbP/I1xLB+g=,tag:GW1fXjTQ4Rnzym4g7BFhNg==,type:str]
        podSecurityContext:
            runAsUser: 1001
            runAsGroup: 1001
            fsGroup: 1001
        ingress:
            enabled: true
            annotations:
                kubernetes.io/tls-acme: "true"
                kubernetes.io/ingress.class: internal
                nginx.ingress.kubernetes.io/auth-url: https://gate.sko.ai/api/verify
                nginx.ingress.kubernetes.io/auth-signin: https://gate.sko.ai/
            hosts:
            -   host: fl.sko.ai
                paths:
                -   path: /
                    pathType: Prefix
            tls:
            -   hosts:
                - fl.sko.ai
                secretName: ingress-cert-flood
        persistence:
            data:
                enabled: true
                storageClass: longhorn
                accessMode: ReadWriteOnce
                size: 1Gi
        resources:
            requests:
                memory: 250Mi
                cpu: 500m
            limits:
                memory: 1500Mi
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-02-09T21:38:24Z'
    mac: ENC[AES256_GCM,data:0dby/xNu7GRz08krKJah6g3e2DgRZ/mlKcK8I1CNgFQHJayuFr955PZKyKtryQuBkn48NJK8xCBjSEp7Dvn3OrunaSV0ta73pTwgpkCd3wIGpLk0iTOUwnOnjf3B5FlNumQWzSyZ5ZyG7EEThkFy6oxoBzkDEu7bNNATvRPFg6s=,iv:UuGxy2r9md234s8y9H/uPZPsUqItYvrjSs5YrVBJ++U=,tag:lBeE1RgPRDVJHlt1C6Ld4w==,type:str]
    pgp:
    -   created_at: '2021-01-29T16:33:52Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQMOA4x50yY5upzjEAwArt6U8b6/vk/zeUDYoAxJwuWvVTAdImF8bn8gprHCdbY/
            xkRx9leID/wRPSbMkYsYhj9ZqZY50njo1+qWVbetYEfVJ3D0mjpPVwqOMMlL/MrE
            iK6Px2hcsXSHTSobvDraQvcdKnmMxLBFTlX013qCIPALzxr3YfC1z3AQ/ZkeFX3v
            tbEBX/zcfiD8RAABiSaFQck3Y+UAO0Uhox7L/hR2+H9uPh//kDq6Hk920I6Dr7S8
            q47JAvvsKlkmCix+y4BD1ltaZgeVZNcG/l4fPIb2rcUeI7FR2+e0zwH3yie/CR65
            Ri5DkptiL+uK7R5IudDQSIKS+J9V5pFjeSPjV/hwFgqEUWjN9WdnzLU6eukpK1+k
            CJGbZ9xVEuUlSdQ64eAOdFoHuc5/R/h7YRhkHMpGqKK6Abz5mbEDnMQMVZqhb+IR
            zFblSQ7TfUV+f0ukk346zZ90eBY5YeSua40C61H1FnaD2AhSMRlcfZn3Lxu+nBxo
            oBgWUK71DhG7d5qDP6+SDAC3PGqAWtiO7snnaY82S3hMeAoFbH3qiClRGJassHOO
            +M1NGyqkpcoELm2EV0P80OALaGTg61EZXAzeDETIvEmPIQ1Nr5gqznrDgsyY2PT7
            YTug4ar6J3VoKPgNyl142GeYsfnyuFMsBrFM0puqhDDXKYUXx0fC4UiR58Cc0oIC
            dqux/YJB9LdoNSK9H7aPHn6wszy8hKPMuuhZCJ2LI8Kg16CEAlw0EjL/qdVejCOW
            7OI5YvG0zWhh7lqhDAN4pXNgIX1F9bh3RuZivrHelJ0awqVfV151RyCvgvuUMv3d
            3d31aVief2obWYZT5/0z1l/nLwXgmhAUcdquz81pJi4yVU8D9Oj2ZFOEZGj75U0j
            TA+vq3BqSKBLTolhu6HULaoPF/ruoArCVZWLKaeawpiUUevtifj6xpDA9lQPb01o
            0GzU8pSrex92fsR65MajWVbdmKd1j955a1rqubKMsKOqxrD7AyQ2ZoRh2p/u5Rlg
            XdptZqsAnm3GQ5/p++Tz5rPSXgGYffaszMI4qbKHUssIu1fTj+Q7LvXKU8C+7jXD
            1UO+ugZEatGkYzm6/Co/Q+mTVTct0wF19kA8rB6t6Hlgx29/esVRDqg+hCxJufCw
            XAqPujgqXENi3U3rhc815ig=
            =BkCZ
            -----END PGP MESSAGE-----
        fp: E940DD1F01DE41AC266825F72E962083AFA12A4D
    encrypted_regex: ((?i)pass)
    version: 3.6.1
