apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: flood
    namespace: default
spec:
    interval: 5m
    chart:
        spec:
            chart: flood
            version: 2.2.1
            sourceRef:
                kind: HelmRepository
                name: k8s-at-home
            interval: 30m
    values:
        controllerType: deployment
        image:
            repository: jesec/flood
            tag: master
            pullPolicy: Always
        env:
            FLOOD_OPTION_RUNDIR: /data
            FLOOD_OPTION_AUTH: none
            FLOOD_OPTION_QBURL: http://qbittorrent:8080
        ingress:
            enabled: true
            annotations:
                kubernetes.io/tls-acme: "true"
                kubernetes.io/ingress.class: internal
                nginx.ingress.kubernetes.io/auth-url: https://gate.sko.ai/api/verify
                nginx.ingress.kubernetes.io/auth-signin: https://gate.sko.ai/
            hosts:
            -   host: fl.sko.ai
                paths:
                -   path: /
                    pathType: Prefix
            tls:
            -   hosts:
                - fl.sko.ai
                secretName: ingress-cert-flood
        persistence:
            data:
                enabled: true
                storageClass: ENC[AES256_GCM,data:21/graSfANCBZg==,iv:lCQr9L0BlgXgX2pB5CfEagSjbJVRPg+Kishd2BJzP0E=,tag:1+rxg+nEeoUrOL970gT8kQ==,type:str]
                accessMode: ReadWriteOnce
                size: 1Gi
        resources:
            requests:
                memory: 250Mi
                cpu: 500m
            limits:
                memory: 1500Mi
    valuesFrom:
    -   kind: Secret
        name: flood-helm-values
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-01-29T15:46:28Z'
    mac: ENC[AES256_GCM,data:if+1pDXOS+uNinCSF58Kcdvkr+6+zIf28B7ql6uIjJFEDSlNRJDt8Awek4sSJiT6ynBPbrHBEQnpRx+HUKjv64NXM4sa0v3e4fcIEJXCkYAGn95jNS4gq8/iDbDHL1Rgo2yWURpPug7HFUyQABHFY531avUc7lK5q5r1/lbemjA=,iv:liKnWSeczbRQ5lrmSvtSOYg8yjQUDWJF9/C4Zaq1pWY=,tag:82YZnvg8qei6fwqknJe9Lw==,type:str]
    pgp:
    -   created_at: '2021-01-29T15:46:28Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQMOA4x50yY5upzjEAv7BngRpj0ENZkWC7tE5fBBvOyMPf7Tgs7BBMSVxTmU4XmQ
            f0ojf/QZxYjdSPuzDlfSlwXQcuzsrYEoNa56IX8lYg9RcaIhcuoAJ0fFb9x5j73f
            6M1dso4izz6W8dKSY7eoSby6ndv/i4fUZLa6r9ZWZAunzswOWDgz1hFmF6u41M88
            sVI8iAjcoxZbA2lXuRo+GqqXDkvs+ileL3NvUnvLvFH3xfs2YJfYWvo0A4lGO0ML
            Y7ry+qBOhx72hxL5piA/+GjguAxplQbPwCxxlhQzCcgIaDW26zhtgxi/NeqcaBMn
            mbmN428XdKmsU8HRw7HwWVQKTASH/Xb6juntSPN9NcMbRy1aCd9PBEfq25ui6wHz
            +ZAntGFmsnzQthDfFyox0O7Qpd0GTnYrsw6NNO/TLd1ZkN97Kf0WtSxJQJI/6MA1
            sL5cnqdv4b9lfu61bPMCw0sR0ABieqqYJgd7Qz0c3c3FMWjAOfniyg7jS4XOmhBD
            QzvaOu6s2/s4Iz2VziBHC/45/ZINwpujYBhNuAhpR3ZG7PeJ8C5GC3vL2znuAiDX
            RwHV+5BHEdMkyKw5Uwc1Y7ii6TQx4v9jdARyn0HT/GUf5oU+0EVx1TzPS9/eUTD7
            HQNCono21ZTEbil+d3nyyN+MSjxIv0KZoPy8JZ49WKmtfNSBgyLIVKgOhZEfHawf
            rYX93kjZARll1p5TPoOqHe1kyy021nhoJ7wpo7mqhJ2CcfVil4Nyjke8XoRCdniw
            Z8/Khf8KgLfar5llJtsKZwpCAFSHkxRIdtORLAB4J8K/MNDaeT+t2W1hWi3qSxD3
            87/SsiPyk7mipjyJ4RCfFiKw/UtULotuomxfwRhDh2/ytXqAP8yhjYBuBvFgFWE4
            kpOuiRZ8lOv79Ba1GMSkLbzMz37OMKPU9pKanBS91NwkGrS9zubGMuHi+pQ7KfeS
            Xv+x7mS8Kmr4ZWvGPEw6i5a9nf8ELfk9m5mNZqklurT5X7ehtoU0l9X4lcR3wDXF
            ccrdDwMeiv45LwRqoPp2RiDSXAEdNTDhAA3Gaj50BVrFZown4JdRP9KUVXkcX6rp
            sPo8f4FZ2NBeLrRqbQBlki+04hloZ/NqkoIZe9xYRqKSkKAJwBsiovqngtQcEvlQ
            VsEoQ48r7F4M7IiIvzli
            =haoO
            -----END PGP MESSAGE-----
        fp: E940DD1F01DE41AC266825F72E962083AFA12A4D
    encrypted_regex: ^storageClass$
    version: 3.6.1
