version: '3'
services:
  node-exporter:
    image: ghcr.io/vaskozl/prometheus-node-exporter:1.12.1@sha256:57060bb6c5e0a18904f2f0b3276be54ca1c4840ea23bb822891c9b33b13afa34
    container_name: node-exporter
    network_mode: host
    volumes:
      - /:/host:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro
      - /run/udev/data:/host/root/run/udev/data:ro
    command:
      - --web.listen-address=127.0.0.1:9100
      - --path.rootfs=/host/root
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.udev.data=/host/root/run/udev/data
    restart: unless-stopped
