# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/statefulset-apps-v1.json
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: claude
spec:
  template:
    spec:
      containers:
        - name: claude
          resources:
            requests:
              memory: 768Mi
