---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-hdd-raid-pv-torrent
  namespace: torrent
spec:
  storageClassName: hdd-raid-torrent
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: blind
    path: /srv/nfs
  mountOptions:
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - rsize=32768
    - wsize=32768
