apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: torrent
resources:
- _namespace.yaml
- rtorrent/deployment.yaml
- hdd-raid-pvc.yaml  
- hdd-raid-pv.yaml
- flood/flood.yaml
- sort/torrent-sort-configmap.yaml 
- sort/torrent-sort-cron.yaml

configMapGenerator:
  - name: rtorrent-config
    files:
      - rtorrent/rtorrent.rc
