apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: drone-values
    namespace: default
stringData:
    values.yaml: ENC[AES256_GCM,data:ResnCj36AbP8ZfyAgf5dK8qDMO4XnjuuoQqwPstCM8En1EXCHt53cywYQq2K70CuBjxVJj0Pp4w16/k8HK9LQOFh6LG00kwB1HUEMP/ahZgDBjd0wLxq2ES0WV6IYFBqUYu01wixCw8O1k8W1ScoqAf4W9HLg/Ftkeu0+uHfNznQErJp6s2tF3+nrqo0gDCCbi5WC2N/+/udy/Xi1BEnv6udA8EG5ZnoYr9SbBWCHCNmdv3da4uhaGvinBdy4YPHjuw=,iv:TJypJtfs6WyTLZGARj6d3auUgpCEvcLlpv6WvqPH64g=,tag:P3K4xLQz/KxoTFrYGFlizw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-01-21T00:24:43Z'
    mac: ENC[AES256_GCM,data:g9jlF+lhl4qSqbsWhyJfQ8V69LNZdFACcSKKPKDtJs+3zQTjJxzgTAKLyysEkTulEDqUS0JvFjIREPTedezuUzoo7oWf0QBn98MTCYvEeKyJlCrXmmzrxdftTzuCsRfaPm0WnO18EP2MlLzwXLIeM95nQcCe/dbAZWXcTWZElOQ=,iv:R/uiVaY+T6FEqWGhVZ9JEtatEeAqss7pesvgNIng6Mc=,tag:/SZn+Hc40TtSpQ+6SvosgQ==,type:str]
    pgp:
    -   created_at: '2021-01-21T00:11:05Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQMOA2lPFCwQ/p0LEAv+MVXxGBG2+aUOGR5t3fuTLPgetRb3Cub8lSkurU/WTlCU
            0a4v+sCTdIXRx5s4x9myj0xOd+Ak7+/YS2CQK0btks5xSvNF402GPAxfG9ttRp5e
            tJmBOYVulLpc41JqJIn5LX9dNyJSXU19wXv1L6lpqu+6R6pYhvHzG1nmLS9kkqsz
            Fw8mxNF8AwK7zLuVXwAtilyi/fgsr+VIn3m1Zdm+rweevSGYHORlAup6YsewD0nB
            p8Ps+ElQTA+LsxPRhynQApvXFX2oM6eZqAq1+uWXo8HXLJ8MXsEdIMdsCDzw3Tz4
            iAZIhOBOzbdt9hh36XljYvOdtd371Ow7EqAkw/3lDfnAj0Sa9pcIXMuL3Kjdgraw
            ooiYuLJfUn+D1wjCgtFIRb2gAi4+gCBwAgj4yG8hya1sKZoDhzkM9zyy5h1yWjIS
            wQVa8nYKSIAjeNsV8H6VSZ9KbzOUarKGg9XVUXfGjn3bJnHKyOShqfh/W/jM3Jgt
            RXE1WZnQowkMzmEJGKPqDAC2cLo7NpirGtoYTrz5igHt25CIGU2G2TUPDnZ9E8VU
            Has42rtzQ7/xAgwVTp25XYJVRgpN2DTCVzRYqKyrioVr0UwMPQwFrlqYS6/emHdk
            FL8CcO0bvISd4hwzO86SnfGttI0RlxzwWWXMgWNIP69XsOGI4G+ApcTLro70FDlE
            SQYVX05+h1NY+KZ0elHl5SNZR3jUpQMIeVXe/2CqvpsRNUYaw7EapqWKyRSF1RpI
            2LfoxMDd1G7Snlydc9H0Oe65rp+CZgU3KbW4EvM03pHtOKII7lZo79WO6VY8tBGo
            w4WfTUYxgPL/5CuXAIa0uQhbdNDIesrxSSZb6oOKUEVusQpzRC85Y0LZ9LFJCUZF
            pshqIZMsqWzTtRKHxs3zcSmlKI4Dglv0mkImf/uIwGBUVW3Y/0fWXVbNgU5iCrOj
            DVg2BdVMd+z9vwFknRrumJdr+ug+PAOmFi4AeGdbt2XIr364feVtTfZ1CsnLFC7m
            A0LJtHhrwjgloofPcViEJMbSXgE+wk5goDh7H48IhSIpylHA1QzwnwUvjBWEBBQK
            q4c1CO3A0ahXvXh/n494UA21VHE8yu1+3T0CZpqYlCq65xt9vwTcHDkFnGm622YW
            NJrKyi8M9GfDqTDezxkosDU=
            =iO2e
            -----END PGP MESSAGE-----
        fp: 8C966C744C61FF4B3B0FCB32B1D0320D90555B70
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
