---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone-runner-kube
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: drone-runner-kube
      version: 0.1.5
      sourceRef:
        kind: HelmRepository
        name: drone-charts
      interval: 1h
  values:
    env:
      DRONE_RPC_HOST: drone
      DRONE_RPC_PROTO: http
      DRONE_NAMESPACE_DEFAULT: default
  valuesFrom:
  - kind: Secret
    name: drone-runner-values
