apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: drone-runner-kube
    namespace: default
spec:
    interval: 1h
    chart:
        spec:
            chart: drone-runner-kube
            version: 0.1.5
            sourceRef:
                kind: HelmRepository
                name: drone-charts
            interval: 1h
    values:
        env:
            DRONE_RPC_HOST: drone
            DRONE_RPC_PROTO: http
            DRONE_NAMESPACE_DEFAULT: default
            DRONE_RPC_SECRET: ENC[AES256_GCM,data:2xrDpGz8q9hVVbY1kmQQebR+8uK59+dw2OuJhmGwmuA=,iv:SQ5YnrGZQlc5+yUwXAuCsMkxbZfjf/Fj3wxOC41uqYs=,tag:fbkXb+YO3TVdqAfLxm5ZgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-01-30T00:58:29Z'
    mac: ENC[AES256_GCM,data:Z3XAsBp1CQbSK9IQA0z2Q+w/gttj3kgWPEiHr6YtnoEwcy/nUsbYgwq30PG0ENsn5IbrWe87KhgHcv2hq8oncVsL/RU32gOexNZBSMJ0PShwPdBhBq5i9/R0I937zrIPB2Uu7vLO0b0clw+9LVAg0kEzuY1OgI7BP3vq32oOnJ8=,iv:8T5VyAx2/xeHNnu1oJ3tPRU1RvoJwHOo8FBvX+qYqBo=,tag:QKlnY3wHCrGRloJwAKq/1w==,type:str]
    pgp:
    -   created_at: '2021-01-30T00:58:28Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQMOA4x50yY5upzjEAv/W7tcOoIRzx2gyTPZ0SGil7ntNsyvM3BnIQ0nkP4n+RGG
            Kw9r5G2o1mFTEUjokx+z3Ai+MRwZxExZPal5q4axtKSLdnHTHJmwIHj6N+zaKKQ1
            BrKhN75AyCDIbsHiMOFvulD7uBXRWxn7fdW/gCDffmGG6JTsBDV1NWWO1Xkb7KQc
            Vod8v2kUWxrKcSO+dKGrlFqDu0cueWXoun4/KS+DnpeyVuk5KBH+APSWrhD5JH2t
            LRHhNcigaSl8AtgY82/7p1YKalZTmqcOKXBkaKNG3bN4KJCxcLYP0uCmbZuWqRMl
            BDDraQvNq5RpyvBS0bO54RIpz8T3kCrV0KjYEim1v0xmOUJkudA1C1VVCJ6co+wk
            zAVPiM3cGMx2/QtYX3REMEPI6Eq9+fdNJ5LyunGbnNAeWltNRdymNL+pX/e9a7De
            IRGxbfhj94c4MW7swLEdsDDylSViDfxEMQHMf/V9MoImCSBv6V5wLfKAoVSvuAYM
            vqN6s9W/JSZyK6Aj0IV4DACHvrLLnkAwYl9Jc/rMAgl59wwaGgjIQ9O+Ad3oM6Va
            45KswukK1TLxo7WFmQlG4fxRwkS8UV8ZYl5IXIWgf5I1L5w9+VagG7CIEHicFftB
            9ayI4xsKahH8/WcCRGShoW32E+3P8cS8Xvj3WWSRJbLceFAKrpUcrPv0k8bDde1T
            CmE61w9pXHaqaBj4o5WW35SuWfnCHJxnvhBCvKnm3EIV3QA3Is9Ql/5KLEZITmuB
            SwHoYZQhPZFeNuTrNjCRDtVjAvG/T/ZfXwhlnD/5mTgGXOzfYm0jSgToMpNt1Hff
            lMIdLXtL4slhDdgFxY/lL7OMHSD3GcYs6YjVmI0XnKnAfVdTn4184nlf3o5mrkw9
            WOOYfPHOd8fT0ctuaDjde6tlKr0bw1oR//9qh7WWiU+vmCVuTF3YsWqJI9RDHFic
            //7vvW3emHwtPKX/nGW7Cl0HEzfmdtqEz8QwApAqTSDMFR6EZ/yEs+uCU2EpPV6R
            XVnCJ8KAblpVdnYS1H8gZAXSXAGp0Ftlx5W+5YX7dHfeACr0wDLDRkbSlJ0eoXg7
            1gDwjWnbx2ghBz7puNQ9JmWDpgvnEs1XJI00+DaXYPxl3QR7UVYrh3GUBAe4U0iQ
            rZ+3XIchlPasl/rWRZVP
            =pyHt
            -----END PGP MESSAGE-----
        fp: E940DD1F01DE41AC266825F72E962083AFA12A4D
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData$))
    version: 3.6.1
