# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 24h
  chart:
    spec:
      chart: gitlab
      version: 10.0.2
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      interval: 24h
  values:
    global:
      extraEnv:
        GITLAB_LOG_LEVEL: 'error'
        GITLAB_LOGGER_TRUNCATE_LOGS: true
      nodeSelector:
        kubernetes.io/arch: amd64
      edition: ce
      hosts:
        domain: sko.ai
      ingress:
        enabled: false
        configureCertmanager: false
      gatewayApi:
        enabled: false
        configureCertmanager: false
      kas:
        enabled: false
      pages:
        enabled: false
      email:
        display_name: 'GitLab'
        from: 'gitlab@sko.ai'
        reply_to: 'noreply@sko.ai'
      smtp:
        enabled: true
        address: 'mail.sko.ai'
        port: 2225
        tls: false
        authentication: ''
      redis:
        host: gitlab-redis
        auth:
          secret: gitlab-redis-secret
          key: secret
      psql:
        host: gitlab-postgresql
        password:
          secret: gitlab-postgresql-password
          key: postgresql-password
      minio:
        enabled: false
      appConfig:
        omniauth:
          enabled: true
          autoSignInWithProvider: []
          syncProfileFromProvider: [openid_connect]
          allowSingleSignOn: [openid_connect]
          allowBypassTwoFactor: [openid_connect]
          syncProfileAttributes: [email]
          blockAutoCreatedUsers: false
          providers:
            - secret: pi-oauth2
        lfs: &rails
          connection:
            secret: object-storage
            key: rails.minio.yaml
        artifacts: *rails
        uploads: *rails
        packages: *rails
        externalDiffs: *rails
        terraformState: *rails
        dependencyProxy: *rails
        ciSecureFiles: *rails
    # Reduce memory usage
    gitlab:
      gitlab-exporter:
        enabled: false
      gitaly:
        resources:
          requests:
            cpu: 80m
            memory: 660M
          limits:
            memory: 660M
      webservice:
        minReplicas: 1
        maxReplicas: 2
        # https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/examples/ref/2k.yaml
        workerProcesses: 1
        resources:
          limits:
            memory: 2560Mi
          requests:
            cpu: 100m
            memory: 2560Mi
      sidekiq:
        minReplicas: 1
        maxReplicas: 2
        resources:
          limits:
            memory: 1750Mi
          requests:
            cpu: 50m
            memory: 1300Mi
      gitlab-shell:
        minReplicas: 1
        maxReplicas: 2
        extraVolumes: |
          - name: var-log-gitlab-shell
            emptyDir: {}
        extraVolumeMounts: |
          - name: var-log-gitlab-shell
            mountPath: /var/log/gitlab-shell
      toolbox:
        backups:
          objectStorage:
            config:
              secret: object-storage
              key: toolbox.minio.toml
    registry:
      storage:
        secret: object-storage
        key: registry.minio.yaml
    # Disable things we handle by ourselves
    installCertmanager: false
    nginx-ingress:
      enabled: false
    prometheus:
      install: false
    grafana:
      enabled: false
    gitlab-runner:
      install: false
  postRenderers:
    - kustomize:
        patches:
          - patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: dummy-app
              spec:
                template:
                  spec:
                    nodeSelector:
                      kubernetes.io/arch: amd64
            target:
              kind: Deployment
          - patch: |-
              apiVersion: apps/v1
              kind: StatefulSet
              metadata:
                name: dummy-app
              spec:
                template:
                  spec:
                    nodeSelector:
                      kubernetes.io/arch: amd64
            target:
              kind: StatefulSet
