# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-postgresql
  annotations:
    patch.sko.ai/app-template: common
spec:
  interval: 24h
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 5.0.1
  values:
    controllers:
      main:
        containers:
          app:
            env:
              POSTGRES_USER: postgres
              POSTGRES_DB: gitlabhq_production
              POSTGRES_PASSWORD:
                secretKeyRef:
                  name: gitlab-postgresql-password
                  key: postgresql-postgres-password
            image:
              repository: pgautoupgrade/pgautoupgrade
              tag: 17.10-alpine@sha256:3f2cb0524a5a832301ceec27f01ff953b95d248db26544cb743e972737972187
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  exec:
                    command: [pg_isready, -U, gitlab, -d, gitlabhq_production]
              readiness: *probe
              startup:
                <<: *probe
                spec:
                  exec:
                    command: [pg_isready, -U, gitlab, -d, gitlabhq_production]
                  periodSeconds: 30
                  failureThreshold: 120
            resources:
              limits:
                memory: 1Gi
              requests:
                cpu: 50m
                memory: 768Mi
        statefulset:
          podManagementPolicy: Parallel
          volumeClaimTemplates:
            - accessMode: ReadWriteOnce
              globalMounts:
                - path: /var/lib/postgresql/data
                  subPath: data
              name: data
              size: 8Gi
        type: statefulset
    defaultPodOptions:
      securityContext:
        fsGroup: 70
        runAsGroup: 70
        runAsUser: 70
        runAsNonRoot: true
    service:
      main:
        controller: main
        ports:
          postgresql:
            port: 5432
