# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-redis
  annotations:
    patch.sko.ai/app-template: common
spec:
  interval: 24h
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 4.6.2
  values:
    controllers:
      main:
        containers:
          app:
            envFrom:
              - secretRef:
                 name: gitlab-redis-secret
            args: ["--requirepass", "$(secret)"]
            image:
              repository: ghcr.io/vaskozl/redis
              tag: 8.6.2@sha256:a7c415bb8f461bf00370c85dbe03449e63affe3b90a6f6f6c6095371685a617a
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              limits:
                memory: 250Mi
              requests:
                cpu: 10m
                memory: 250Mi
        statefulset:
          podManagementPolicy: Parallel
        type: statefulset
    service:
      main:
        controller: main
        ports:
          redis:
            port: 6379
