# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
      version: v1.20.2
  interval: 24h
  values:
    image:
      repository: ghcr.io/vaskozl/cert-manager-controller
      tag: 1.20.2@sha256:e9051938db0aa83c464161ab2e50f6c9dbbeb38e29994b8c6f2dfd3ee014b8dc
    cainjector:
      replicaCount: 1
      image:
        repository: ghcr.io/vaskozl/cert-manager-cainjector
        tag: 1.20.2@sha256:dc2b0c7718ef3623b8e089eef943a31ab5b242df49a304cd89896c5ffe9e99b1
    acmesolver:
      image:
        repository: ghcr.io/vaskozl/cert-manager-acmesolver
        tag: 1.20.2@sha256:e541474151fbd00e6445e2256b0f80257f6f82cfc000ea9488b234a5308776c0
    webhook:
      image:
        repository: ghcr.io/vaskozl/cert-manager-webhook
        tag: 1.20.2@sha256:089c66bee124aa02dd33fdf422efa30cc2f426b49c33afd80a7a9ab4dabf4d38
    installCRDs: true
    extraArgs:
      - --dns01-recursive-nameservers=1.1.1.1:53
    podDnsPolicy: None
    podDnsConfig:
      nameservers:
        - 1.1.1.1
        - 8.8.8.8
    # Enabled once prometheus-operator is installed
    prometheus:
      enabled: false
      servicemonitor:
        enabled: false
        namespace: cert-manager
    config:
      apiVersion: controller.config.cert-manager.io/v1alpha1
      kind: ControllerConfiguration
      enableGatewayAPI: true
