# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
      version: v1.20.2
  interval: 24h
  values:
    image:
      repository: ghcr.io/vaskozl/cert-manager-controller
      tag: 1.20.2@sha256:22187d1b891851a2ebcb2cc184d583dd099801dac9111612728c8655d8acca83
    cainjector:
      replicaCount: 1
      image:
        repository: ghcr.io/vaskozl/cert-manager-cainjector
        tag: 1.20.2@sha256:3d9da5fa5e5575a1387db597d2477f04fc97e9244ad22c96af5005e484aacfba
    acmesolver:
      image:
        repository: ghcr.io/vaskozl/cert-manager-acmesolver
        tag: 1.20.2@sha256:09b63ced439715f551802e8ee224f95a990677e9ece89e3c0dada48ba6e58a9c
    webhook:
      image:
        repository: ghcr.io/vaskozl/cert-manager-webhook
        tag: 1.20.2@sha256:06fcc2c2ff2c25e7c66d046009f777a24ac01147f8ec89ff09e92bfb078bb025
    installCRDs: true
    extraArgs:
      - --dns01-recursive-nameservers=1.1.1.1:53
    podDnsPolicy: None
    podDnsConfig:
      nameservers:
        - 1.1.1.1
        - 8.8.8.8
    # Enabled once prometheus-operator is installed
    prometheus:
      enabled: false
      servicemonitor:
        enabled: false
        namespace: cert-manager
    config:
      apiVersion: controller.config.cert-manager.io/v1alpha1
      kind: ControllerConfiguration
      enableGatewayAPI: true
