---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.20.2
  url: oci://quay.io/jetstack/charts/cert-manager
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chartRef:
    kind: OCIRepository
    name: cert-manager
  interval: 24h
  values:
    image:
      repository: ghcr.io/vaskozl/cert-manager-controller
      tag: 1.20.2@sha256:93aa49989d50f6d96386832b8949b9cd65dae421f506c552c559e953ab19dd29
    cainjector:
      replicaCount: 1
      image:
        repository: ghcr.io/vaskozl/cert-manager-cainjector
        tag: 1.20.2@sha256:28d799a0c233b50e5d917578aa23bc022e84dc96dade8031f0bb151ca6332e1d
    acmesolver:
      image:
        repository: ghcr.io/vaskozl/cert-manager-acmesolver
        tag: 1.20.2@sha256:e9ef874afc9373c84cc9a0d6cc857a0fcb6613618866c8cc6c071c8b9092ccc4
    webhook:
      image:
        repository: ghcr.io/vaskozl/cert-manager-webhook
        tag: 1.20.2@sha256:1fa5d81672a4e6bc02b730defa6696d35e74e7858675363e95232a8253b35a56
    installCRDs: true
    extraArgs:
      - --dns01-recursive-nameservers=1.1.1.1:53
    podDnsPolicy: None
    podDnsConfig:
      nameservers:
        - 1.1.1.1
        - 8.8.8.8
    # Enabled once prometheus-operator is installed
    prometheus:
      enabled: false
      servicemonitor:
        enabled: false
        namespace: cert-manager
    config:
      apiVersion: controller.config.cert-manager.io/v1alpha1
      kind: ControllerConfiguration
      enableGatewayAPI: true
