---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.21.2
  url: oci://quay.io/jetstack/charts/cert-manager
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chartRef:
    kind: OCIRepository
    name: cert-manager
  interval: 24h
  values:
    image:
      repository: ghcr.io/vaskozl/cert-manager-controller
      tag: 1.20.4@sha256:c0459525b7c4bf14339ba9edbcd15d0775380adbda7295110a8367766373015d
    cainjector:
      replicaCount: 1
      image:
        repository: ghcr.io/vaskozl/cert-manager-cainjector
        tag: 1.20.4@sha256:91e9dacc682439e393515854b05168f7d21cb895c7018b90aa4a1f608b5765b9
    acmesolver:
      image:
        repository: ghcr.io/vaskozl/cert-manager-acmesolver
        tag: 1.20.4@sha256:e1661def59b398c5ea8f28eb34310b79c912eb251bd78c3296f96d8a406edcae
    webhook:
      image:
        repository: ghcr.io/vaskozl/cert-manager-webhook
        tag: 1.20.4@sha256:3355b367d7e8a7710aea268bdbfac6c051513fab884172b9e36b17c434f0680a
    installCRDs: true
    extraArgs:
      - --dns01-recursive-nameservers=1.1.1.1:53
    podDnsPolicy: None
    podDnsConfig:
      nameservers:
        - 1.1.1.1
        - 8.8.8.8
    # Enabled once prometheus-operator is installed
    prometheus:
      enabled: false
      servicemonitor:
        enabled: false
        namespace: cert-manager
    config:
      apiVersion: controller.config.cert-manager.io/v1alpha1
      kind: ControllerConfiguration
      enableGatewayAPI: true
