apiVersion: batch/v1
kind: CronJob
metadata:
  name: scanner
spec:
  schedule: "0 7 * * 2,6"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: scanner-sa
          containers:
            - name: scanner-container
              image: ghcr.io/vaskozl/perl-mojolicious:9.41@sha256:8c933c4fb395da67ebe18ce62d75d1dfd68c0b0430b48174afd9a456e22c4c04
              args:
                - /script/scan-containers.pl
                - -u
                - -m=pixel@ntfy.sko.ai
                - -s=ntfy.automation.svc.cluster.local
              volumeMounts:
                - name: script
                  mountPath: /script
          volumes:
            - name: script
              configMap:
                name: script
