# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/statefulset-apps-v1.json

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scanner
spec:
  serviceName: scanner
  template:
    spec:
      serviceAccountName: scanner-sa
      containers:
        - name: scanner-container
          image: ghcr.io/vaskozl/wolfi-scanner:0.0.4@sha256:831c38ab0a934065bb2ecac1ac8dd63b93200a94bd64549ad27f4afe05f88e7c
          args: [-image-filter, 'ghcr.io/vaskozl,cgr.dev/']
          ports:
            - name: metrics
              containerPort: 9090
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: scanner
spec:
  selector:
    matchLabels:
      app: scanner
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 300s
