apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scanner
spec:
  serviceName: scanner
  template:
    spec:
      serviceAccountName: scanner-sa
      containers:
        - name: scanner-container
          image: ghcr.io/vaskozl/wolfi-scanner:0.0.4@sha256:2e675c9b1b6de907239ca720cf8fc139e791db4d3eb1816ac09f3123ab7bb52f
          args: [-image-filter, 'ghcr.io/vaskozl,cgr.dev/']
          ports:
            - name: metrics
              containerPort: 9090
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: scanner
spec:
  selector:
    matchLabels:
      app: scanner
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 300s
