---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-client-provisioner
  namespace: kube-system
spec:
  chart:
    spec:
      chart: nfs-client-provisioner
      sourceRef:
        kind: HelmRepository
        name: helm-stable
      version: 1.2.11
  interval: 1h
  values:
    image:
      repository: quay.io/external_storage/nfs-client-provisioner-arm
      tag: v3.1.0-k8s1.11
    nfs:
      server: "pi0"
      path: "/srv/nfs"
      mountOptions:
        - tcp
        - intr
        - hard
        - noatime
        - nodiratime
        - rsize=32768
        - wsize=32768
    storageClass:
      defaultClass: true
