# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - agentgateway/ks.yaml
  - ai/ks.yaml
  - argo-workflows
  - automation
  - cert-manager/ks.yaml
  - cloudflared
  - default
  - flux-system
  - gitlab
  - golink
  - haproxy
  - headlamp
  - immich
  - keda/ks.yaml
  - kube-flannel
  - kube-system
  - logging
  - mail
  - matcha
  - media
  - minilb
  - nfs-subdir
  - oauth2-proxy
  - pocket-id
  - rbac
  - renovate
  - sing-box
  - synology-csi
  - vaultwarden
  - victoria-metrics/ks.yaml
