apiVersion: v1
kind: Service
metadata:
  name: doods
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: doods
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doods
spec:
  selector:
    matchLabels:
      app: doods
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: doods
    spec:
      containers:
      - image: snowzach/doods:latest
        name: doods
        env:
        ports:
        - containerPort: 8080
          name: doods
        resources:
          requests:
            cpu: "1000m"
            memory: 1.0Gi
          limits:
            memory: 1.1Gi
