kind: ServiceAccount
apiVersion: v1
metadata:
  name: jellyfin-restart
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jellyfin-restart
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["statefulsets"]
    resourceNames: ["jellyfin"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jellyfin-restart
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jellyfin-restart
subjects:
  - kind: ServiceAccount
    name: jellyfin-restart
    namespace: media
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: jellyfin-restart
spec:
  concurrencyPolicy: Forbid
  schedule: '0 4 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: jellyfin-restart
          containers:
            - name: kubectl
              image: ghcr.io/vaskozl/kubectl@sha256:94da9f6d25e58c7153890f46e8b9512219b2b4b505286041f9d86e315d6bedc2
              args: [rollout, restart, sts/jellyfin]
