kind: ServiceAccount
apiVersion: v1
metadata:
  name: jellyfin-restart
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jellyfin-restart
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["statefulsets"]
    resourceNames: ["jellyfin"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jellyfin-restart
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jellyfin-restart
subjects:
  - kind: ServiceAccount
    name: jellyfin-restart
    namespace: media
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: jellyfin-restart
spec:
  concurrencyPolicy: Forbid
  schedule: '0 4 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: jellyfin-restart
          containers:
            - name: kubectl
              image: ghcr.io/vaskozl/kubectl:1.35@sha256:fec92d449fa6279a8130358dfa68f82f9ee936456f1676641fe8411a41fb6d33
              args: [rollout, restart, sts/jellyfin]
