kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mojopaste
  annotations:
    volume.beta.kubernetes.io/storage-class: "rook-ceph-block"
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Mi
