---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: longhorn-system
      interval: 5m
  values:
    persistence:
      defaultClassReplicaCount: 2
    defaultSettings:
      defaultReplicaCount: 2
      defaultDataPath: /var/lib/rancher/longhorn
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "internal"
        nginx.ingress.kubernetes.io/auth-url: "https://gate.sko.ai/api/verify"
        nginx.ingress.kubernetes.io/auth-signin: "https://gate.sko.ai/"
      host: lh.sko.ai
      tlsSecret: ingress-cert-longhorn
      tls: true
