kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: code-server-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "rook-ceph-block"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
