---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
  annotations:
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: google
      version: 0.12.0
  interval: 1m0s
  values:
    controller:
      image:
        repository: metallb/controller
        tag: v0.9.3
    speaker:
      image:
        repository: metallb/speaker
        tag: v0.9.3
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.1.16-192.168.1.63
