apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: speedtest
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "internal"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      sendfile on;
      access_log off;
      gzip off;
      fastcgi_read_timeout 999;
      log_not_found  off;
      server_tokens off;
      error_page  405     =200 $uri;
      error_log /dev/null;
      tcp_nodelay on;
      tcp_nopush on;
      open_file_cache max=200000 inactive=20s;
      open_file_cache_valid 30s;
      open_file_cache_min_uses 2;
      open_file_cache_errors on;
spec:
  rules:
  - host: st.sko.ai
    http:
      paths:
      - backend:
          serviceName: speedtest
          servicePort: 8080
        path: /
  tls:
  - hosts:
    - st.sko.ai
    secretName: ingress-cert-speedtest
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: speedtest
  type: LoadBalancer
  loadBalancerIP: 192.168.1.45
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest
spec:
  selector:
    matchLabels:
      app: speedtest
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      containers:
      # This is the only image they have..
      - image: openspeedtest/latest:speedtest
        name: speedtest
        env:
        ports:
        - containerPort: 8080
          name: speedtest
