{
 "title": "NFS Full",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_boot_time_seconds, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "NFS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "NFS Connections",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_nfs_connections_total[$__rate_interval]",
     "legendFormat": "Number of NFS TCP connections"
    }
   ]
  },
  {
   "title": "NFSd Connections",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_nfsd_connections_total{job=~\"$job\"}",
     "legendFormat": "Number of NFSd TCP connections"
    }
   ]
  },
  {
   "title": "NFS Packets",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_nfs_packets_total{protocol=\"tcp\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "TCP - NFS network packets (sent+received)"
    },
    {
     "expr": "rate(node_nfs_packets_total{protocol=\"udp\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "UDP - NFS network packets (sent+received)"
    }
   ]
  },
  {
   "title": "NFSd Packets",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_nfsd_packets_total{proto=\"tcp\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "TCP - NFSd network packets (sent+received)"
    },
    {
     "expr": "rate(node_nfsd_packets_total{proto=\"udp\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "UDP - NFSd network packets (sent+received)"
    }
   ]
  },
  {
   "title": "NFS RPC",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_nfs_rpc_authentication_refreshes_total{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Number of RPC authentication refreshes performed"
    },
    {
     "expr": "rate(node_nfs_rpc_retransmissions_total{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Number of RPC transmissions performed"
    },
    {
     "expr": "rate(node_nfs_rpcs_total{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Total number of RPCs performed"
    }
   ]
  },
  {
   "title": "NFSd RPC",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_nfsd_rpc_errors_total{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ error }} - NFSd RPC errors"
    },
    {
     "expr": "rate(node_nfsd_server_rpcs_total{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "NFSd RPCs"
    }
   ]
  },
  {
   "title": "NFSd Disk Read / Write",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_nfsd_disk_bytes_read_total{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "NFSd bytes read"
    },
    {
     "expr": "rate(node_nfsd_disk_bytes_written_total{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "NFSd bytes written"
    }
   ]
  },
  {
   "title": "NFS File Handles",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_nfsd_file_handles_stale_total{job=~\"$job\"}[$__rate_interval]",
     "legendFormat": "NFSd stale file handles"
    }
   ]
  },
  {
   "title": "NFS Cache",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_nfsd_read_ahead_cache_not_found_total{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "NFSd read ahead cache not found"
    },
    {
     "expr": "rate(node_nfsd_reply_cache_hits_total{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "NFSd Reply Cache hits (client lost server response)"
    },
    {
     "expr": "rate(node_nfsd_reply_cache_misses_total{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "NFSd Reply Cache an operation that requires caching (idempotent)"
    },
    {
     "expr": "(node_nfsd_reply_cache_nocache_total{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "NFSd Reply Cache non-idempotent operations (rename/delete/…)"
    }
   ]
  },
  {
   "title": "NFSd Server Threads",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_nfsd_server_threads{job=~\"$job\"}",
     "legendFormat": "NFSd kernel threads that are running"
    }
   ]
  },
  {
   "title": "NFS v4 Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "NFS v4 NFS Procedures Invoked 1",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(node_nfs_requests_total{method='Access',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='Commit',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='Create',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='FsInfo',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='GetAttr',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='Link',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='Lookup',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='Null',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='Allocate',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='BindConnToSession',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='Clone',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "NFS v4 NFS Procedures Invoked 2",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "rate(node_nfs_requests_total{method='PathConf',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='Read',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='ReadDir',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='ReadLink',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='Rename',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='Setattr',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='SymLink',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='Write',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='Close',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='CreateSession',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='Read',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "NFS v4 NFS Procedures Invoked 3",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "rate(node_nfs_requests_total{method='DeAllocate',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='DelegReturn',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='DestroyClientID',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='DestroySession',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='ExchangeID',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='FreeStateID',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='FsLocations',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='FsidPresent',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='GetACL',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='GetDeviceInfo',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "NFS v4 NFS Procedures Invoked 4",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 87 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "rate(node_nfs_requests_total{method='GetDeviceList',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='GetLeaseTime',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='LayoutCommit',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='LayoutGet',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='LayoutReturn',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='LayoutStats',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='Lock',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='Lockt',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='Locku',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='Lookup',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "NFS v4 NFS Procedures Invoked 5",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(node_nfs_requests_total{method='LookupRoot',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='Open',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='OpenConfirmt',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='OpenDowngrade',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='OpenNoattr',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='ReclaimComplete',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='ReleaseLockowner',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='Renew',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='Secinfo',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='SecinfoNoName',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "NFS v4 NFS Procedures Invoked 6",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(node_nfs_requests_total{method='Seek',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='Sequence',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='ServerCaps',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='SetACL',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='SetClientID',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='SetClientIDConfirm',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='StatFs',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfs_requests_total{method='TestStateID',proto='4',job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      }
     ]
    }
   ]
  },
  {
   "title": "NFSd v4 Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {}
   ]
  },
  {
   "title": "NFSd v4 NFSd Requests by Method 1",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_nfsd_requests_total{method='Access',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Commit',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Create',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='GetAttr',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Link',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Lookup',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Close',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='DelegPurge',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='DelegReturn',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='GetFH',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "NFSd v4 NFSd Requests by Method 2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_nfsd_requests_total{method='Read',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='ReadDir',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='ReadLink',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Remove',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Rename',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='SetAttr',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Write',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Lock',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Lockt',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Locku',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "NFSd v4 NFSd Requests by Method 3",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_nfsd_requests_total{method='LookupRoot',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Nverify',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Open',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='OpenAttr',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='OpenConfirm',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='OpenDgrd',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='PutFH',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='RelLockOwner',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Renew',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='RestoreFH',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='SaveFH',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='SecInfo',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Verify',proto='4',job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    }
   ]
  }
 ]
}