# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/statefulset-apps-v1.json
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: claude-worker-opus
spec:
  template:
    spec:
      containers:
        - name: claude
          command: [ralph-dev]
          env:
            - name: ANTHROPIC_MODEL
              value: opus
          volumeMounts:
            - name: ralph
              mountPath: /usr/local/bin/ralph-dev
              subPath: ralph-dev.sh
            - name: ralph
              mountPath: /etc/claude/prompt.md
              subPath: prompt.md
      volumes:
        - name: ralph
          configMap:
            name: ralph-dev
            defaultMode: 0555
