apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: redis
    includeSelectors: true

generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled

configMapGenerator:
  - name: redis-scripts
    files:
      - scripts/lib.sh
      - scripts/sentinel.sh
      - scripts/redis.sh
      - scripts/prestop.sh
      - scripts/push-master-label.sh
      - scripts/update-master-label.sh

resources:
  - rbac.yaml
  - svc.yaml
  - sts.yaml
