apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: redis
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: redis
subjects:
  - kind: ServiceAccount
    name: redis
