apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis-headless
  replicas: 3
  podManagementPolicy: Parallel
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  template:
    spec:
      securityContext:
        fsGroup: 65532
      terminationGracePeriodSeconds: 30
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      initContainers:
        - name: sentinel
          image: &image ghcr.io/vaskozl/redis:8.8.0@sha256:5ad168ba2affaa0698b6a80a314cc2865c55e791b1ae6f89821613ed0b8fc253
          restartPolicy: Always
          command: ["/scripts/sentinel.sh"]
          env: &env
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: sentinel
              containerPort: 26379
          startupProbe:
            tcpSocket:
              port: sentinel
            periodSeconds: 1
            failureThreshold: 30
          livenessProbe:
            exec:
              command: ["redis-cli", "-p", "26379", "ping"]
          resources:
            requests:
              cpu: 5m
              memory: 20Mi
            limits:
              memory: 20Mi
          volumeMounts: &mounts
            - name: data
              mountPath: /data
            - name: scripts
              mountPath: /scripts
      containers:
        - name: redis
          image: *image
          command: ["/scripts/redis.sh"]
          env: *env
          lifecycle:
            preStop:
              exec:
                command: ["/scripts/prestop.sh"]
          ports:
            - name: tcp
              containerPort: 6379
          livenessProbe: &redis-ping
            exec:
              command: ["redis-cli", "ping"]
          readinessProbe: *redis-ping
          resources:
            requests:
              cpu: 10m
              memory: 150Mi
            limits:
              memory: 150Mi
          volumeMounts: *mounts
      volumes:
        - name: scripts
          configMap:
            name: redis-scripts
            defaultMode: 0555
