apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis-headless
  replicas: 3
  podManagementPolicy: Parallel
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  template:
    spec:
      serviceAccountName: redis
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: redis
                    app.kubernetes.io/instance: redis
      securityContext:
        fsGroup: 65532
      terminationGracePeriodSeconds: 30
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      initContainers:
        - name: sentinel
          image: &image ghcr.io/vaskozl/redis:8.8.0@sha256:f16936f4ddd7bbddcba9888a1b6a67f83d91c7190723572dcad75ae263df6200
          restartPolicy: Always
          command: ["/usr/local/bin/sentinel.sh"]
          env: &env
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: sentinel
              containerPort: 26379
          startupProbe:
            tcpSocket:
              port: sentinel
            periodSeconds: 1
            failureThreshold: 30
          livenessProbe:
            exec:
              command: ["redis-cli", "-p", "26379", "ping"]
          resources:
            requests:
              cpu: 20m
              memory: 20Mi
          volumeMounts: &mounts
            - name: data
              mountPath: /var/lib/redis
            - name: usr-local-bin
              mountPath: /usr/local/bin
            - name: run-redis
              mountPath: /run/redis
        - name: labeler
          image: ghcr.io/vaskozl/kubectl:1.35@sha256:1244215b02ee388e3153ae7eed80f9023c47f22103cb57e8d7f079cc7435f2cf
          restartPolicy: Always
          command: ["/usr/local/bin/update-master-label.sh"]
          env: *env
          readinessProbe:
            exec:
              command: ["test", "-e", "/proc/1/fd/3"]
            periodSeconds: 5
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
          volumeMounts:
            - name: usr-local-bin
              mountPath: /usr/local/bin
            - name: run-redis
              mountPath: /run/redis
      containers:
        - name: redis
          image: *image
          command: ["/usr/local/bin/redis.sh"]
          env: *env
          lifecycle:
            preStop:
              exec:
                command: ["/usr/local/bin/prestop.sh"]
          ports:
            - name: tcp
              containerPort: 6379
          livenessProbe: &redis-ping
            exec:
              command: ["redis-cli", "ping"]
          readinessProbe: *redis-ping
          resources:
            requests:
              cpu: 100m
              memory: 150Mi
          volumeMounts: *mounts
      volumes:
        - name: run-redis
          emptyDir: {}
        - name: usr-local-bin
          configMap:
            name: redis-scripts
            defaultMode: 0555
