apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mailserver
  namespace: mailserver
  annotations:
    kubernetes.io/tls-acme: "true"
    acme.cert-manager.io/http01-ingress-class: "external"
    kubernetes.io/ingress.class: "internal"
spec:
  rules:
  - host: mail.sko.ai
    http:
      paths:
      - backend:
          serviceName: http-echo
          servicePort: 80
        path: /mailserver
  tls:
  - hosts:
    - mail.sko.ai
    secretName: ingress-cert-mailserver
