kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mail-storage-data
  namespace: mailserver
  annotations:
    volume.beta.kubernetes.io/storage-class: "rook-ceph-block"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
