---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: default
spec:
  chart:
    spec:
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: mojo2600
      version: 1.7.15
  interval: 1m0s
  values:
    serviceTCP:
      loadBalancerIP: 192.168.1.16
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    serviceUDP:
      loadBalancerIP: 192.168.1.16
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    dnsmasq:
      additionalHostsEntries:
      # Dnsmasq reads the /etc/hosts file to resolve ips. You can add additional entries if you like
        - 192.168.1.10     pi0.lan
        - 192.168.1.11     pi1.lan
        - 192.168.1.12     pi2.lan
        - 192.168.1.16     pihole.lan pi.hole
        - 192.168.1.18     i.lan
    persistentVolumeClaim:
      enabled: true
      existingClaim: pihole
