# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/daemonset-apps-v1.json
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
spec:
  template:
    spec:
      shareProcessNamespace: true
      containers:
        - name: fluent-bit
          image: ghcr.io/vaskozl/fluent-bit:5.0.5@sha256:7dc21e20216532eb2de4b9313fc86e0f065487a5e3ca0201848970a975d2a6d5
          args: [-c, "/config/fluent-bit.yaml"]
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: fluent-bit-config
              mountPath: /config
      terminationGracePeriodSeconds: 10
      tolerations:
        - operator: Exists
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
      serviceAccountName: fluent-bit
