# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/deployment-apps-v1.json

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-deployment
spec:
  replicas: 2
  template:
    spec:
      securityContext:
        sysctls:
          # Allows ICMP traffic
          - name: net.ipv4.ping_group_range
            value: "568 568"
      containers:
        - image: ghcr.io/vaskozl/cloudflared:2026.3.0@sha256:9631d8a5891d6d950092399a40045741119c8e891e1f246bf40d7d42a951b1c1
          name: cloudflared
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tunnel-token
                  key: token
          args:
            - tunnel
            - --no-autoupdate
            - --loglevel
            - info
            - --metrics
            - 0.0.0.0:2000
            - run
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            initialDelaySeconds: 10
            periodSeconds: 10
