apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-deployment
spec:
  replicas: 2
  template:
    spec:
      securityContext:
        sysctls:
          # Allows ICMP traffic
          - name: net.ipv4.ping_group_range
            value: "568 568"
      containers:
        - image: ghcr.io/vaskozl/cloudflared:2026.2.0@sha256:b384801736ca646be16dbf8741680058c715b5bb2f9d17d8637d35f544f2148b
          name: cloudflared
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tunnel-token
                  key: token
          args:
            - tunnel
            - --no-autoupdate
            - --loglevel
            - info
            - --metrics
            - 0.0.0.0:2000
            - run
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            initialDelaySeconds: 10
            periodSeconds: 10
