# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/deployment-apps-v1.json

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-deployment
spec:
  replicas: 2
  template:
    spec:
      securityContext:
        sysctls:
          # Allows ICMP traffic
          - name: net.ipv4.ping_group_range
            value: "568 568"
      containers:
        - image: ghcr.io/vaskozl/cloudflared:2026.5.0@sha256:c69c5de0177ac121fd5524bab3be1a02d415dd1c9cadf1ced5c7155954820c98
          name: cloudflared
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tunnel-token
                  key: token
          args:
            - tunnel
            - --no-autoupdate
            - --loglevel
            - info
            - --metrics
            - 0.0.0.0:2000
            - run
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            initialDelaySeconds: 10
            periodSeconds: 10
