# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/cronjob-batch-v1.json
# yaml-lanaguage-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/cronjob-batch-v1.json
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: '15 2,3,4 * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            kubernetes.io/arch: amd64
          containers:
            - name: renovate
              image: ghcr.io/vaskozl/renovate:43.170.15@sha256:632806352d73e26a578c23cae98abdea6f2ad27a454329ecdb1970291e07070f
              # Environment Variables
              env:
                - name: LOG_LEVEL
                  value: debug
                - name: BINARY_SOURCE
                  value: install
                - name: RENOVATE_ALLOWED_COMMANDS
                  value: |-
                    ["^BASE_REF=HEAD \\.gitlab/bump-epochs\\.pl$"]
              envFrom:
                - secretRef:
                    name: renovate-env
              resources:
                requests:
                  cpu: 740m
                  memory: 1.3Gi
                limits:
                  memory: 1.3Gi
              securityContext:
                allowPrivilegeEscalation: false
          restartPolicy: Never
