# yaml-lanaguage-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/cronjob-batch-v1.json
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: '15 3,4 * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            kubernetes.io/arch: amd64
          containers:
            - name: renovate
              image: ghcr.io/vaskozl/renovate:43.84.0@sha256:951eb8504e0b17cadd107d10c00aade54d8b3ed589d681aaa1079d9a3f984995
              # Environment Variables
              env:
                - name: LOG_LEVEL
                  value: debug
                - name: BINARY_SOURCE
                  value: install
              envFrom:
                - secretRef:
                    name: renovate-env
              resources:
                requests:
                  cpu: 740m
                  memory: 1.3Gi
                limits:
                  memory: 1.3Gi
              securityContext:
                allowPrivilegeEscalation: false
          restartPolicy: Never
