---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
      version: 3.20.1
  interval: 1h
  values:
    controller:
      ingressClass: internal
      kind: DaemonSet
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      hostPort:
        enabled: true
      config:
        proxy-body-size: '0'
        ssl-protocols: "TLSv1.3 TLSv1.2"
        use-proxy-protocol: "true"
        use-forwarded-headers: "true"
        compute-full-forwarded-for: "true"
        global-auth-url: "https://gate.sko.ai/api/verify"
        global-auth-signin: "https://gate.sko.ai"
      resources:
        requests:
          memory: 250Mi
          cpu: 25m
        limits:
          memory: 500Mi
    defaultBackend:
      enabled: false
