---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
      version: 3.20.1
  interval: 1h
  values:
    controller:
      replicaCount: 3
      containerPort:
        http:  9080
        https: 9443
      extraArgs:
        http-port: 9080
        https-port: 9443
      service:
        type: NodePort
        externalIPs:
        - 192.168.99.1
        externalTrafficPolicy: Local
      ingressClass: internal
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - ingress-nginx
              - key: app.kubernetes.io/component
                operator: In
                values:
                - controller
            topologyKey: "kubernetes.io/hostname"
      config:
        proxy-body-size: '0'
        ssl-protocols: "TLSv1.3 TLSv1.2"
        global-auth-url: "https://gate.sko.ai/api/verify"
        global-auth-signin: "https://gate.sko.ai"
        hsts: false
      extraArgs:
        default-ssl-certificate: "cert-manager/sko-ai-tls"
      resources:
        requests:
          memory: 250Mi
          cpu: 25m
        limits:
          memory: 500Mi
    defaultBackend:
      enabled: false
