# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-internal
data:
  "22": gitlab/gitlab-gitlab-shell:22
