# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:i/qSb23AWdafX1df7mhyHEL0XhoTCHAzrXYLMhuw2QtB5tMAnEjsA9/qGlHoFup5wExhsN2+usBkkAeUtLobkuHjujRArt8P7FNWpYZdVPVkKUBBiRhAuLkRKYCKU3hU7U+rwKjaOy63EzwnR2gobjsz6P+cYhMPg99OY8Uwa/uWrdbPUScYcjQC8IqMMZGC9EyrXBFgRUMhZQdichDuwGhXhoqVVLe04XjIdZ66iR0yWbIr7Pwe8EQOpewKkMcJhwJJYRe2Hc8k8JuKy5VFg+01MWQ2LXfR5goPff+E31kIHnuduliykaYQhikFaNFZUJJnqGJhE+usa9G9M7mP3FaPqeFz68Rke/oSqw==,iv:WMqqTpPvKOkRIdvlFct13jrsRfkJOYX6AMb/zj7euIs=,tag:PJscqF8nHWH6mQxxXy0PTQ==,type:str]
sops:
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData$))
  lastmodified: "2026-09-02T08:34:52Z"
  mac: ENC[AES256_GCM,data:1on4YdTxSeMb35mhpW08wt5RZJSGKDi99qsO9MaYIre/T10nI1nq2ZXnpNfRrgXFAj7hpsFBJBvYSk5F4MevTyJrzzcy4cZaeDl8mf4CnrCG5scTWO8BxFiyZf1kax9YHufDgZlM4+uh0PdkXyFrCz/rEJJIWceKuniuUBK9KCU=,iv:smCRCWok7Mv6kO1bjjesxlZ0vpgxJRLHcDqqz7Mijr8=,tag:mzT/IrOzSGGhf3qQH3gIPQ==,type:str]
  pgp:
    - created_at: "2026-09-02T08:34:52Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQMOA4x50yY5upzjEAv+J5ekgoAclNnj985V35TPFRvvuULN4lZc3SLHrDR6vAzM
        9396jsItr8QSkpuAIPmYJbx0bmTt4Y+WnwaAo21Eyajud0DgOIak5tvk0ynLE0gR
        viUUFk0YP9MTPKGSawmI3TjVLKN3xlw7mcOGedd4avLHBbYz9+Fso89iakdSx25U
        qFVg4cmAPKSzhryP7BvFW1izEEXa7/I4hxVqvRt8Yb1ro3pmHBt91BqTLxUHkg35
        FASneCCg3TV1dVQwe6+N3wxbrGWiIvxtiSMlLnrrLWOGjxlZyzW9PcMUKx0ITy8X
        eUfqnwmToVT6Rs3gw01TEqs21nNh0ZyHqsWNLOr/ClGeqt58cQ1iMUhBJVNFndUa
        LGwIc9LiuhG3Ose4JH7YVDZ2+C0LnFN/CFbKJOei/Sy0zA6rIx1XedsWlkbRk8B+
        zSJWsGAEP/tyD1MAQ52bps/K5Js+y4E7Wohru04tdL0JRKNxcPppeyUVcTMu+Ab6
        /LG4ykklVBY/ZzQ/ySoVC/43HZOfsfZh3bpuD7nzYvfXoPm7KdT3mE3NzseC8DoP
        dvK2OaegRraWMUHClNqEhFA0VkZBrX8QkGOiN7Dm76wRTqDBnI1om4zSpN+xUten
        5Ofoi0of/uI0nPCsOtnMrWmBRWhHyLfav0ZFkT5JZBSutE7FgP5U1QRZPs5d6l1e
        YNH542ygWsLH+jKfqctUbxM7fSOhD/WXXD5DTRcgMpFTtB9rU2AAUyKWUB0chd0s
        dc+hiEr9WD0Z6yx2DZYAZPYjNRZcBy3NN/iPhBynXtoQB4I99k7FrYp2i/FYMIa5
        0c6ftRbb5hdgHXXLBzBMTZWu471+ortbgOUm31EGKEj9AK3M5aKALaemN+WojtvA
        rEvQFUPtwSIRyuAL3WiejZNynGb1xdPu7qAHq5Hj1wqoGzsWDQYflp6+d5aCMKh/
        FF7eKqxdQXVwMPbymgSJZgMvq9FBbXl3CFtygBe2sYKsRIHpSeMSdMc1aCgVLg1W
        ikpiX/2Ttyg4b5C/gmrYGnnSXgEfZFPm1QvL4LZDxMb/AM8HlsmZ3A2QgBtRXxqN
        C7GuFDiS1HEBscMq62Z8gb91Qnpc7CLHcV0X/+KQA6R6MADC+OId/PQoXgcQiR+s
        Nu7UTRIRQBecCqyvRAHKVEw=
        =1dM8
        -----END PGP MESSAGE-----
      fp: E940DD1F01DE41AC266825F72E962083AFA12A4D
  version: 3.13.2
