apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  creationTimestamp: null
  name: gotk-system
  namespace: gotk-system
spec:
  interval: 5m
  ref:
    branch: main
  secretRef:
    name: gotk-system
  url: ssh://git@github.com/vaskozl/home-infra
status: {}
