# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/persistentvolumeclaim-v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrents-v2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: torrents-pv-media-v2
  resources:
    requests:
      storage: 1Mi
