apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: sftp
    namespace: default
strinData:
    sssd.conf: |
        [sssd]
        config_file_version = 2
        services = nss, pam
        debug_level = 5

        [pam]

        [nss]
        fallback_homedir = /home/%u
        default_shell = /usr/sbin/nologin
    sftp.json: |
        {
          "users": [
            {
              "PublicKeys": ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDb93dk1TfpbUOPtSaN3+t5YwxrwWPywikeqQ/yWlxaqsPsKWjaTAweiro4Hfv1XWci84H/XINARylQrt3e3F7hTh+EFKUgnkTyc4cs53etXaL9eS4IluMDM2DIpKis/nXnMBI3rli0eoxGCoxSobY0MEi1qoNPpn/95WZ3m3cT/9O05+fmW0yZgEwN+O3HkySCsevBIxbRyKsGBBzpvxXaBcjRmKe7c5MyYsIhlZb0nWH5aGWSPS2QM3WO9ku3OlxAPkek8f7xCW2pBU9BCFCNFMfMwWCrwDBYNg/aqCQ7YtXQIXgmX7DLPKD3axse1igGvh8xl+NWfwhBTlSk6fmd v@skozl.com",
              "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCeR7bWDm4iAvmK7xGraJCdbB57TQAprVa2s0JfaXTlY4dwsGwUMJ7hJ0ksSdY5McNehNmM5Nj/SGNqYgJmo0b5rnBMdlBXU8h9P7XfOTh+w2WWqAj8jB6gjrelihzecaNtbyIkpA4ldxuZgHNFeP5HuLAWdZnPZEiCBhMBRNB7K1ul/SC1nWHiU4oG8LaWY0h703gRDL9oUAQBt0u1NE66NTZU9b8avqsHJjvo5wEBvwdX+/VjlewyqVcBTzDdTEqECEKOZCTNO39nNZEEU8MvkyCIwkyRsax4buHwI0s9d6xwsLN6rZ5QB5UkRKEXuXBYMzJj33m0PDiZ7DgshZAE5q81/v1u1e547vuH+p9xXsLGgxQSZoq17UrOL+U2o1uDYnG7Qs8an7WuFeYZN6OxC8TRsfbg1JVT5Ek7OjDalGvOtww1P7qRCTXftu0gID6PDbw+zMWY1Lq+wYLU1nhALfVY4BYbXOInfTxGf/zZ2hGOtlMZC2rqR5/AAG5HdM= vsz@photosync"],
              "Username": "vsz"
            }
          ]
        }
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-01-20T23:58:37Z'
    mac: ENC[AES256_GCM,data:m4hPE9IGSqOQIW1xnpbKVSGz+mRxRpW6xnS2aM2cBr/h4Os3xkOrzO7Zze8xrAly1hDcv0V6Z+hGuLEb0dXYnzeAa6RZWJ/mNekxMjMrmUHKdzxtb8ezpP9cGVtTPMpR6W5bXQOCgvuO37iOw8IlBJ2rEH9zEWtnsY2akFIvE1k=,iv:KgcLmqe3SrghzfwGPlQlGHInhXtfWxADKhVRUx6+9x0=,tag:erxJwNgB29aNaG+vtrGkLQ==,type:str]
    pgp:
    -   created_at: '2021-01-20T23:58:00Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQMOA2lPFCwQ/p0LEAv+KLJd+MSEzNEJ2WrVBsGRoHmzBXUro6AcOqa5TpPwXrQP
            /HcHK/KY9gnD0RJwQFK5yL/oh8KKbsrBAxN9BCva+lYgg2WWzVtNk+qkwuuY78VU
            KuxUaGJv6O6giqU9Ea2uXvYZAekvuEn9AexIqwPK9TqeEsMoEYNO8/o18L/T14Wl
            4OD9vu7OA/InMo6Z0Sg9WUBTUbjKYrvDO8aOs0OViSnIDg4Gl84dB8tmJYqIwlZw
            SY4UB/NeBehV3U4d0Bpmf0bH4LUNtDodaKFoPTsmBNCGEQtSZkrdPL8m6nG3HMS0
            WhSeQa87CjHP7Q7DKSpvs/v7GAD+sqLB/OTbUmUd81i/B5wCrJ/tih8ltC2DbKOO
            S6aI17Hr5KVrCna7SevUbalpHsNYIL0gAQpnHcspZTiMfJ1HBfZ/QBDBQHsbRaoX
            WGh7jNNUo1ARzOCigi8K7zU5xNdMOmoOi2fCHWu+bDRYr/dZoKI4k3idyZCB6Dlk
            LT4coY8Co32ki8CF4xt6C/wIYDrwOR7KbSZWDSYpbBSVPYz3jjFfwocAgXvjPwzH
            6nn2JQwp3GtPCTXdCM9j/SjC3cGF+3yR3GQtcQpwSf43dpRt+F+/Q8E9/gnJF6Tc
            1q4oHNkAg1KfqLF1RSxn7YHvng5ICiI2yGj6UPO8Quoljz2a0T12uinbJQYzBkRT
            hpjaFImc0V+5QZWNZk7KwIAxpf2BeVIWj8zLWM6fJa3aSLeO5vIk3KvRUbUn3ZIR
            AD/RYymUXFTDCAEf4STKL8YPo9jtx/KijiQnJWB6l07XZ7phV9IoofUroPjJ/rHw
            ShnEgy4HipIitv4w+kwai3qhUJl4A2yd6telaWGH3HNuA9LIJJQ4SklPiuEdwri7
            qN+Q8RboC0QHFnWhS3IVwkoZu4IJlVQ5JdNRuNsT0LJqrTqmD/lbsm8Pr9p7gWoI
            tB3u09TdhGSWhPwNNHksN/35H/Fa5xjRBgziFTf2kfA9Kav31O9JCNqGEpwC4qyE
            3ngsnQBO5Rz4nYfCkha6Xw/SXgFAvJSefZZp2UnalO2kgzmpkLHE4udUjSq952OK
            Y+xxP5W+uhiFKYZfS7o8sNFbuINJZrSYG5tsm8uhGR0Q38+kUx920Sup6Iq0TLNH
            WZyeMrlGBMSwzyPYDus0mUE=
            =LlnV
            -----END PGP MESSAGE-----
        fp: 8C966C744C61FF4B3B0FCB32B1D0320D90555B70
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
