apiVersion: batch/v1
kind: CronJob
metadata:
  name: shelly-brightness
spec:
  schedule: '0 */1 * * *'
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  jobTemplate:
    metadata:
    spec:
      template:
        metadata:
        spec:
          containers:
            - args: [/script/shelly-brightness.pl]
              image: ghcr.io/vaskozl/perl-libwww:6.81@sha256:7c124192a8cf60372936e7c3852e828e32e2a3cdd3920404274a64fb68b696f4
              name: shelly-brightness
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
                limits:
                  cpu: 100m
                  memory: 256Mi
              volumeMounts:
                - mountPath: /script
                  name: script
          restartPolicy: Never
          volumes:
            - configMap:
                defaultMode: 420
                name: script
              name: script
