# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/cronjob-batch-v1.json
apiVersion: batch/v1
kind: CronJob
metadata:
  name: shelly-brightness
spec:
  schedule: '0 */1 * * *'
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  jobTemplate:
    metadata:
    spec:
      template:
        metadata:
        spec:
          containers:
            - args: [/script/shelly-brightness.pl]
              image: ghcr.io/vaskozl/perl-libwww:6.82@sha256:cbc47426cb9740203405fdae62d3e5acb833f852c45cab614d6f83e3a5832499
              name: shelly-brightness
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
                limits:
                  cpu: 100m
                  memory: 256Mi
              volumeMounts:
                - mountPath: /script
                  name: script
          restartPolicy: Never
          volumes:
            - configMap:
                defaultMode: 420
                name: script
              name: script
