---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
spec:
  chart:
    spec:
      chart: gitea
      sourceRef:
        kind: HelmRepository
        name: gitea
      version: 2.1.3
  interval: 1h
  values:
    image:
      repository: gitea/gitea
      tag: 1.13.1
    persistence:
      enabled: true
      #storageClass: "nfs-client"
      existingClaim: gitea-pvc
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "internal"
        nginx.ingress.kubernetes.io/auth-url: "https://gate.sko.ai/api/verify"
        nginx.ingress.kubernetes.io/auth-signin: "https://gate.sko.ai/"
      hosts:
      - "git.sko.ai"
      tls:
      - hosts:
        - "git.sko.ai"
        secretName: ingress-cert-gitea
    gitea:
      cache:
        builtIn:
          enabled: false
      database:
        builtIn:
          postgresql:
            enabled: false
      config:
        database:
          DB_TYPE: postgres
          HOST: cockroachdb-public:26257
          NAME: gitea
          USER: root
          PASSWD: gitea
          SCHEMA: gitea
  
