apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- setup.yaml
- flux-repo.yaml
- graf-ingress.yaml
- main.yaml
- prom-ingress.yaml
- flux-dashboards.yaml
- ceph-dashboards.yaml

