---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-prometheus
  namespace: flux-system
spec:
  dependsOn:
  - name: kube-prometheus-setup
  interval: 1h0m0s
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube-prometheus
  timeout: 2m0s
  patchesStrategicMerge:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: kube-state-metrics
        namespace: monitoring
      spec:
        template:
          spec:
            containers:
            - name: kube-state-metrics
              image: k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.0.0-beta
    # Add Grafana dashboards and disable password
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: grafana
        namespace: monitoring
      spec:
        template:
          spec:
            containers:
            - name: grafana
              env:
              - name: GF_AUTH_BASIC_ENABLED
                value: "false"
              - name: GF_AUTH_ANONYMOUS_ENABLED
                value: "true"
              - name: GF_AUTH_ANONYMOUS_ORG_ROLE
                value: Admin
              volumeMounts:
              - name: grafana-dashboard-k8s-flux
                mountPath: /grafana-dashboard-definitions/0/flux
            volumes:
            - name: grafana-dashboard-k8s-flux
              configMap:
                name: grafana-dashboard-k8s-flux
                defaultMode: 420
    # Let prometheus scrape all namespaces (like flux-system)
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: prometheus-k8s
      rules:
      - apiGroups:
        - ""
        resources:
        - nodes
        - nodes/metrics
        - services
        - endpoints
        - pods
        verbs: ["get", "list", "watch"]
      - apiGroups:
        - extensions
        resources:
        - ingresses
        verbs: ["get", "list", "watch"]
      - nonResourceURLs:
        - /metrics
        verbs:
        - get
