---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: prometheus-operator-crds
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./example/prometheus-operator-crd
  targetNamespace: monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: prometheus-operator
  validation: client

