# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    patch.sko.ai/app-template: common
  name: vaultwarden
spec:
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 5.0.0
  interval: 24h
  values:
    controllers:
      vaultwarden:
        containers:
          app:
            env:
              ROCKET_PORT: 8080
            image:
              repository: ghcr.io/dani-garcia/vaultwarden
              tag: 1.36.0@sha256:d626d04934cd1192ad8ced1adb975099fca78cec33ab467d2d3c923cde7f3b0c
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              limits:
                memory: 100Mi
              requests:
                cpu: 100m
                memory: 100Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
        statefulset:
          podManagementPolicy: Parallel
          volumeClaimTemplates:
            - accessMode: ReadWriteOnce
              globalMounts:
                - path: /data
              name: data
              size: 1Mi
        type: statefulset
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        runAsGroup: 568
        runAsNonRoot: true
        runAsUser: 568
        seccompProfile:
          type: RuntimeDefault
    route:
      app:
        annotations:
          gethomepage.dev/description: Password Manager
          gethomepage.dev/enabled: 'true'
          gethomepage.dev/group: Cloud
          gethomepage.dev/icon: bitwarden
          gethomepage.dev/name: Bitwarden
        hostnames:
          - bw.sko.ai
        parentRefs:
          - name: internal-noauth
            namespace: agentgateway
    service:
      app:
        controller: vaultwarden
        ports:
          http:
            port: 8080
