# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: net-tools
  annotations:
    patch.sko.ai/app-template: common
spec:
  interval: 24h
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 5.0.1
  values:
    controllers:
      net-tools:
        type: statefulset
        containers:
          app:
            command:
              - sleep
              - inf
            image:
              repository: ghcr.io/vaskozl/net-tools
              tag: 2.10@sha256:5701c02706a097711fb1cfb99de92cae1b2c7e9a21ab538d846efb4e10d2281a
            resources:
              requests:
                cpu: 10m
                memory: 10Mi
