# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/cronjob-batch-v1.json
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ci-monitor
spec:
  schedule: '17 * * * *'
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  jobTemplate:
    metadata:
    spec:
      template:
        metadata:
        spec:
          containers:
            - args: [/script/ci-monitor.pl]
              image: ghcr.io/vaskozl/perl-mojolicious:9.41@sha256:a9c3761d7b7d597153c7bf8089a934693e191a5907caa54400ca84bcdd49fec8
              name: ci-monitor
              envFrom:
                - secretRef:
                    name: claude-env
              resources:
                requests:
                  cpu: 20m
                  memory: 64Mi
                limits:
                  memory: 128Mi
              volumeMounts:
                - mountPath: /script
                  name: script
          restartPolicy: Never
          volumes:
            - configMap:
                defaultMode: 420
                name: ci-monitor-script
              name: script
