# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - cron.yaml
configMapGenerator:
  - name: ci-monitor-script
    files:
      - ci-monitor.pl
