apiVersion: v1alpha1
kind: authproviders
spec:
  name: pi
  type: oidc
  displayName: Pocket ID
  icon: fingerprint
  issuer: "https://pi.sko.ai"
  clientId: "0022f43f-7b1e-4daf-a0fa-d76955c70b30"
  clientSecretEnv: OIDC_CLIENT_SECRET
  scopes:
    - openid
    - profile
    - email
  emailVerifiedRequired: true
  enabled: true
