---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hass
  namespace: default
spec:
  chart:
    spec:
      chart: home-assistant
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
      version: 5.2.1
  interval: 1h
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 0.117.6
    env:
      TZ: "Europe/London"
    persistence:
      config:
        enabled: true
        size: 10Gi
        storageClass: "nfs-client"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "internal"
        nginx.ingress.kubernetes.io/enable-global-auth: "false"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          location /local {
            deny all;
            return 403;
          }
      hosts:
        - host: "ha.sko.ai"
          paths:
          - path: /
            pathType: Prefix
      tls:
      - hosts:
        - "ha.sko.ai"
        secretName: ingress-cert-hass
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.30
    hostNetwork: false
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
    resources:
      limits:
        memory: 500Mi
      requests:
        cpu: 35m
        memory: 150Mi
