---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hass
  namespace: default
spec:
  chart:
    spec:
      chart: home-assistant
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
      version: 2.0.0
  interval: 1h
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 0.117.6
    extraEnv:
      TZ: "Europe/London"
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "nfs-client"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "internal"
      hosts:
      - "ha.sko.ai"
      tls:
      - hosts:
        - "ha.sko.ai"
        secretName: ingress-cert-hass
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.30
    hostNetwork: true
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
    vscode:
      enabled: false
    resources:
      limits:
        memory: 1000Mi
      requests:
        cpu: 35m
        memory: 800Mi
    monitoring:
      enabled: false
